Make JDK HttpClient customizable
spring-cloud/spring-cloud-openfeign pull request #1000
Opened 2024-03-14 12:19 UTC by driverpt

Fixes #999

2024-03-19 14:09 UTC, OlgaMaciaszek requested changes
Hello @driverpt, thanks for creating the PR. Please address the comments. Also, please add a test (you can use Spring Boot's `ApplicationContextRunner`).

2024-03-19 14:09 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/Http2ClientFeignConfiguration.java
> +import java.util.List;
Please update the year in the license to `2013-2024`.

2024-03-19 14:09 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/Http2ClientFeignConfiguration.java
> +	@Bean
Please add empty line between methods.

2024-03-19 14:09 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/http2client/Http2ClientCustomizer.java
> +
Please add javadocs for class and method.

2024-03-20 10:29 UTC, OlgaMaciaszek requested changes
Thanks @driverpt . LGTM. Just one more cosmetic things in the javadocs - please address.

2024-03-20 11:42 UTC, OlgaMaciaszek approved these changes
Thanks @driverpt. LGTM.

2024-03-20 11:44 UTC, OlgaMaciaszek requested changes
Acutally, there seem to be checkstyle issues. Please fix.

2024-03-20 12:00 UTC, driverpt commented
Done!

2024-03-20 12:18 UTC, OlgaMaciaszek approved these changes
LGTM.

2024-03-20 12:19 UTC, merged