SpringMvcContract support parse params
spring-cloud/spring-cloud-openfeign pull request #1016
Opened 2024-04-04 06:58 UTC by Puppy4C

Previously, SpringMvcContract did not support parsing the `params` parameter of @RequestMapping.

Example:

1. Define a rest interface that uses the `params` parameter：
```
@PutMapping(value = "/user", params = "action=disable")
public String disableUser() {
    return "user";
}
```
2. Define a FeignClient to call the previously declared interface：

```
@FeignClient("user-server")
static interface UserService {
    @PutMapping(value = "/user", params = "action=disable")
    String disableUser();
}
```

When sending this request, the request path will be resolved to `/user` instead of `/user?action=disable`, resulting in 400 errors.
Therefore, this PR provides the ability to parse `params` parameter。

2024-04-04 06:58 UTC, pivotal-cla commented
@Puppy4C Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=1016)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=1016) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-04-04 06:59 UTC, pivotal-cla commented
@Puppy4C Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=1016)!

2024-04-18 15:31 UTC, OlgaMaciaszek requested changes
Thanks for the PR, @Puppy4C. Have added some comments - please take a look.

2024-04-18 15:31 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
> +	private void parseParams(MethodMetadata data, Method method, RequestMapping methodMapping) {
Please add documentation for this feature in `spring-cloud-openfeign.adoc`.

2024-04-18 15:31 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
> +				this.isNegated = expression.startsWith("!");
Please remove unnecessary `this.` keywords.

2024-04-18 15:31 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringMvcContractTests.java
> +	void testProcessAnnotations_ParseParams_SingleParam() throws Exception {
Please add a tests to verify  behaviour when both `params=` and `@RequestParam` annotation present.

2024-04-18 15:31 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
> +			if (!nameValueResolver.isNegated()) {
I know it was handled for headers, but it actually does not make much sense to have negated values on client side; I think we  should not handle them at all (i.e. throw an exception), because adding them on client side indicates the client-side API has not been thought through.

2024-04-20 10:20 UTC, Puppy4C commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
> +			if (!nameValueResolver.isNegated()) {
I think it's good. Fixed

2024-04-20 10:20 UTC, Puppy4C commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringMvcContractTests.java
> +	void testProcessAnnotations_ParseParams_SingleParam() throws Exception {
Fixed

2024-04-20 10:20 UTC, Puppy4C commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
> +				this.isNegated = expression.startsWith("!");
Fixed

2024-04-20 10:20 UTC, Puppy4C commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
> +	private void parseParams(MethodMetadata data, Method method, RequestMapping methodMapping) {
Fixed

2024-04-22 13:10 UTC, OlgaMaciaszek requested changes
Thanks @Puppy4C. The implementation looks good, but the documentation should be slightly more robust. I have added a comment. Please address.

2024-04-22 13:10 UTC, OlgaMaciaszek commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +	@PostMapping(value = "/stores/{storeId}", consumes = "application/json", params = "mode=upsert")
Please add a description of the feature, including information on what syntax is allowed and to what resulting query params it will be resolved.

2024-04-25 09:05 UTC, OlgaMaciaszek approved these changes
Thanks @Puppy4C. LGTM.

2024-04-25 09:07 UTC, OlgaMaciaszek commented
@Buzzardo could you please review the documentation changes?

2024-05-07 14:32 UTC, Buzzardo requested changes

2024-05-07 14:32 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +Spring Cloud OpenFeign provides support for the Spring `@RequestMapping` annotation and its derived annotations (such as `@GetMapping`, `@PostMapping`, etc.) support.
Change `etc.` to `and others`.

2024-05-07 14:32 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +The attributes on the `@RequestMapping` annotation (including `value`, `method`, `params`, `headers`, `consumes`, and `produces`) will be parsed by `SpringMvcContract` as the content of the request.
Change `will be` to `are`.

2024-05-07 14:32 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +For example:
Change to `Consider the following example:`

2024-05-07 14:32 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +In the above example, the request url will be resolved to `/stores/{storeId}?mode=upsert`. +
Change `will be` to `is`.

2024-05-07 14:32 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +The params attribute also supports the use of multiple `key=value` or only one `key`. For example: +
Remove `. For example`

2024-05-07 14:32 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +- When `params = { "key1=v1", "key2=v2" }`, the request url will be parsed as `/stores/{storeId}?key1=v1&key2=v2`.
Change `will be` to `is`.

2024-05-07 14:32 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +- When `params = "key"`, the request url will be parsed as `/stores/{storeId}?key`.
Change `will be` to `is`.

2024-05-09 13:07 UTC, Puppy4C commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +Spring Cloud OpenFeign provides support for the Spring `@RequestMapping` annotation and its derived annotations (such as `@GetMapping`, `@PostMapping`, etc.) support.
Done, thanks a lot!

2024-05-09 13:07 UTC, Puppy4C commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +The attributes on the `@RequestMapping` annotation (including `value`, `method`, `params`, `headers`, `consumes`, and `produces`) will be parsed by `SpringMvcContract` as the content of the request.
Done

2024-05-09 13:07 UTC, Puppy4C commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +For example:
Done

2024-05-09 13:07 UTC, Puppy4C commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +In the above example, the request url will be resolved to `/stores/{storeId}?mode=upsert`. +
Done

2024-05-09 13:07 UTC, Puppy4C commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +The params attribute also supports the use of multiple `key=value` or only one `key`. For example: +
Done

2024-05-09 13:07 UTC, Puppy4C commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +- When `params = { "key1=v1", "key2=v2" }`, the request url will be parsed as `/stores/{storeId}?key1=v1&key2=v2`.
Done

2024-05-09 13:07 UTC, Puppy4C commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> +- When `params = "key"`, the request url will be parsed as `/stores/{storeId}?key`.
Done

2024-05-09 13:11 UTC, Puppy4C commented
Hi @OlgaMaciaszek，Done

2024-05-13 12:37 UTC, OlgaMaciaszek approved these changes
Thanks @Puppy4C. LGTM.

2024-05-13 12:45 UTC, merged

2024-08-01 11:54 UTC, sondemar commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
> +			if (!nameValueResolver.isNegated()) {
> I know it was handled for headers, but it actually does not make much sense to have negated values on client side; I think we should not handle them at all (i.e. throw an exception), because adding them on client side indicates the client-side API has not been thought through.

Hi @OlgaMaciaszek ,

Is it possible to change the access modifier of the parseParams method (and other parse* methods) in this Contract from private to protected? This would allow for greater accessibility and potential subclassing, enabling us to enrich the [Contract](https://javadoc.io/doc/io.github.openfeign/feign-core/latest/feign/Capability.html#enrich-feign.Contract-). 

Note: We use generated APIs from the same OpenAPI specifications for intercommunication between our Spring-based applications, which use the same interfaces for both the Feign client and REST controller.

Thank you!