Adds ignorecase field to pageable spring
spring-cloud/spring-cloud-openfeign pull request #1047
Opened 2024-07-30 00:16 UTC by gklp

Adds ignorecase field to pageable spring for compatibility with SortHandlerMethodArgumentResolverSupport::parseIgnoreCase

2024-09-04 09:44 UTC, OlgaMaciaszek requested changes
Hi, @gklp. Thanks for submitting the PR. Have added some cosmetic comments - please address them. Also, please update the date in the license comments of any files you've modified to `2013-2024` .

2024-09-04 09:44 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +			assertThat(order.isIgnoreCase()).as("isIgnoreCase has not expected value.").isEqualTo(true);
Please rephrase the message to "isIgnoreCase does not have expected value"

2024-09-04 09:44 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		assertThat(firstOrder.isIgnoreCase()).as("isIgnoreCase has not expected value.").isEqualTo(true);
Please rephrase the message to "isIgnoreCase does not have expected value"

2024-09-04 09:44 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		assertThat(secondOrder.isIgnoreCase()).as("isIgnoreCase has not expected value.").isEqualTo(false);
Please rephrase the message to "isIgnoreCase does not have expected value"

2024-09-12 05:19 UTC, gklp commented
all issues were resolved @OlgaMaciaszek

2024-09-12 09:06 UTC, OlgaMaciaszek requested changes
Hi @gklp, it still needs one minor change - please see the comment.

2024-09-12 09:06 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +			assertThat(order.isIgnoreCase()).as("isIgnoreCase has not expected value.").isEqualTo(true);
Please rephrase the message to "isIgnoreCase does not have expected value"

2024-09-12 09:12 UTC, gklp commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +			assertThat(order.isIgnoreCase()).as("isIgnoreCase has not expected value.").isEqualTo(true);
All "isIgnoreCase has not expected value." descriptions were changed.

2024-09-12 10:45 UTC, OlgaMaciaszek approved these changes
Thanks @gklp. LGTM.

2024-09-12 14:30 UTC, merged