Make Content-Encoding configurable
spring-cloud/spring-cloud-openfeign pull request #1071
Opened 2024-09-08 13:53 UTC by AndreTeigler

A new configuration property was added to make the Content-Encoding configurable when using the feign request compression. The default values are the same as the previous hardcoded values.

Fixes gh-1048

2024-09-10 18:11 UTC, OlgaMaciaszek requested changes
Hi @AndreTeigler, thanks for the PR. Have requested some changes, mostly minor. Please address the comments.

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +	void apply_SizeEqualsThreshold_NoCompressionHeader() {
Please rename to `shouldNotAddCompressionHeaderWhenSizeEqualsThreshold`

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +	void apply_SizeAboveThreshold_DefaultCompressionHeader() {
Please rename to `shouldAddCompressionHeaderWhenSizeAboveThreshold`

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +		assertThat(template.headers().containsKey(HttpEncoding.CONTENT_ENCODING_HEADER)).isFalse();
Change to `assertThat(template.headers()).doesNotContainKey(HttpEncoding.CONTENT_ENCODING_HEADER);`

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +		assertThat(template.headers().containsKey(HttpEncoding.CONTENT_ENCODING_HEADER)).isFalse();
Also please change in other tests when more specific assertions can be used instead of `isFalse` or `isTrue`.

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +	void apply_MimeTypeMismatch_NoCompressionHeader() {
Please rename to `shouldNotAddCompressionHeaderWhenTypeMismatch`.

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +	void apply_NoMimeTypeSet_DefaultCompressionHeader() {
Please rename to `shouldAddDefaultCompressionHeaderWhenMimeTypeNotSet`.

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +	void apply_NullMimeTypeSet_DefaultCompressionHeader() {
Please rename to `shouldAddDefaultCompressionHeaderWhenNullMimeTypeSet`.

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +	void apply_NonDefaultContentEncodingSet_CustomCompressionHeader() {
Please rename to `shouldAddCustomCompressionHeader`.

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +	void apply_NoContentEncodingsSet_DefaultCompressionHeader() {
This test will need changing after behaviour change.

2024-09-10 18:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTest.java
> +		final var properties = new FeignClientEncodingProperties();
This test will need changing after behaviour change.

2024-09-12 19:47 UTC, AndreTeigler commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptor.java
> +		if (getProperties().getContentEncodings() != null && getProperties().getContentEncodings().length > 0) {
I wanted to stay inline with the code in 'matchesMimeType' but I see the point that this is too silent. I just fallback to the default without informing the user that something went wrong.

What about logging a warning and then use the fallback value? Would still be inline with the property evaluation behavior in this class but would give the user a chance to see the misconfiguration?

2024-09-12 20:00 UTC, AndreTeigler commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptor.java
> +		if (getProperties().getContentEncodings() != null && getProperties().getContentEncodings().length > 0) {
I added the log as suggestion, but I can also throw an exception if this is more appropiate.

2024-09-13 09:37 UTC, OlgaMaciaszek requested changes
Thanks a lot @AndreTeigler. I have added some more comments.

2024-09-13 09:37 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptor.java
> +		log.warn("Invalid content encoding configuration, falling back to default.");
Many users may ignore warnings and if  they changed something in that prop, it means they expected something other than the default prop value to appear there. I think it's better if they know something went wrong, so I think we should throw something like an `IllegalStateException` instead.

2024-09-13 09:37 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTests.java
> + * Unit tests for {@link FeignContentGzipEncodingInterceptor}
Please add a full stop at the end of this line.

2024-09-13 09:37 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTests.java
> +
Please remove this empty line, so that the test only has 2 sections divided by empty lines: Arrange: all preliminary setup, A

2024-09-13 09:37 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTests.java
> +	void shouldAddDefaultCompressionHeaderWhenNullContentEncodingTypes() {
Test should be modified after implementation is adjusted.

2024-09-13 09:37 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptorTests.java
> +		final FeignClientEncodingProperties properties = new FeignClientEncodingProperties();
Test should be modified after implementation is adjusted.

2024-09-15 07:01 UTC, AndreTeigler commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptor.java
> +		log.warn("Invalid content encoding configuration, falling back to default.");
I try to read warnings in my apps :).

2024-09-16 11:38 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptor.java
> +		log.warn("Invalid content encoding configuration, falling back to default.");
So do many users, but if we know that the user has explicitly opted out of the default behaviour by changing sth in the properties file, they should get an exception rather than the default behaviour they do not expect, as it's always better to know that something hasn't gone as expected.

2024-09-25 11:17 UTC, OlgaMaciaszek approved these changes
Thanks @AndreTeigler. LGTM.

2024-09-25 11:23 UTC, merged