Implemented feature requested in #284
spring-cloud/spring-cloud-openfeign pull request #415
Opened 2020-10-08 17:59 UTC by IlyasYOY

Hello! 

I've tried to implement feature I requested in Issue #284 
TBH I just updated my old solution.

I've got some likes there so I decided to post this PR. 

Thanks you for your work!

2020-10-08 17:59 UTC, pivotal-issuemaster commented
@IlyasYOY Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=415)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=415) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-10-08 18:00 UTC, pivotal-issuemaster commented
@IlyasYOY Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=415)!

2020-10-28 16:33 UTC, OlgaMaciaszek commented
Thanks @IlyasYOY . Will review it tomorrow.

2020-10-29 12:15 UTC, OlgaMaciaszek reviewed
Thanks, @IlyasYOY. The functionality looks good, however, I've added a few comments.

Also, this feature does not break backward compatibility, so it could be added starting with the `Hoxton` release branch. Could you resubmit this PR (or create a new one instead) against `2.2.x` rather than `master`?

Please add your full name with `@author` tag to all the classes you've modified.

Please add a section in the documentation describing this feature (in `spring-cloud-openfeign.adoc`).

2020-10-29 12:15 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +		private Map<String, Collection<String>> defaultRequestParameters;
Let's rename to `defaultQueryParameters`.

2020-10-29 12:15 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingPropertiesTests.java
> +	private FeignClientFactoryBean eggsClientFactoryBean;
Let's rename the factory bean, context and test to something meaningful, like `defaultHeadersAndQueryParams`.

2020-10-29 12:15 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/resources/feign-properties.properties
> +feign.client.config.eggs.defaultRequestHeaders[eggsHeaders]=header
Let's test also for collection values.

2020-10-29 12:15 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/resources/feign-properties.properties
> +feign.client.config.eggs.defaultRequestParameters[eggsParameters]=parameter
Let's test also for collection values.

2020-10-29 12:15 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingPropertiesTests.java
> +		@RequestMapping(method = RequestMethod.GET, path = "/eggs")
Let's switch to `@GetMapping` to be more concise.

2020-10-29 12:17 UTC, OlgaMaciaszek requested changes
See the other comments.

2020-10-29 12:49 UTC, OlgaMaciaszek commented
Fixes gh-284.

2020-10-29 12:57 UTC, IlyasYOY commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingPropertiesTests.java
> +		@RequestMapping(method = RequestMethod.GET, path = "/eggs")
Solved, also replaced all `RequestMapping` entries in this file.

2020-10-29 12:57 UTC, IlyasYOY commented on spring-cloud-openfeign-core/src/test/resources/feign-properties.properties
> +feign.client.config.eggs.defaultRequestParameters[eggsParameters]=parameter
Added `pawsTest`, that checks that option

2020-10-29 12:58 UTC, IlyasYOY commented on spring-cloud-openfeign-core/src/test/resources/feign-properties.properties
> +feign.client.config.eggs.defaultRequestHeaders[eggsHeaders]=header
Added pawsTest, that checks that option

2020-10-29 12:58 UTC, IlyasYOY commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingPropertiesTests.java
> +	private FeignClientFactoryBean eggsClientFactoryBean;
Renamed. `defaultHeadersAndQuerySingleParamsFeignClientFactoryBean`

2020-10-29 12:59 UTC, IlyasYOY commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +		private Map<String, Collection<String>> defaultRequestParameters;
Renamed. `defaultQueryParameters`

2020-10-29 13:45 UTC, IlyasYOY commented
I'll open a new PR with the changes, but applied on 2.2.x branch!

Thanks for review comments!

2020-10-29 13:53 UTC, IlyasYOY commented
@OlgaMaciaszek Moved all the work on 2.2.x branch

You can check it here: https://github.com/spring-cloud/spring-cloud-openfeign/pull/415

I guess this PR may be closed.

2020-10-29 13:53 UTC, closed without merging