Fixes gh-391 timeout handling documentation
spring-cloud/spring-cloud-openfeign pull request #421
Opened 2020-10-29 23:09 UTC by Nikolas-Charalambidis

This should fix https://github.com/spring-cloud/spring-cloud-openfeign/issues/391

I have created a whole new section as long as I believe the timeout handling configuration is something almost always to be customized by developers. 

Please review it. I am open to leave it as is, move it as a part of another section or create a subsection of an existing one.

2020-10-30 12:49 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +When Hystrix <<spring-cloud-openfeign#spring-cloud-feign-hystrix,is enabled>> its timeout configuration link:https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutIn
maybe rather: prevents it from happening

2020-10-30 12:49 UTC, OlgaMaciaszek commented
Fixes gh-391.

2020-10-30 16:09 UTC, Nikolas-Charalambidis commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +When Hystrix <<spring-cloud-openfeign#spring-cloud-feign-hystrix,is enabled>> its timeout configuration link:https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutIn
Makes sense. I have reworded the sentence.

2020-10-30 16:27 UTC, OlgaMaciaszek commented
Thanks, @Nikolas-Charalambidis. Let's wait for a review from @Buzzardo.

2020-10-30 16:38 UTC, Buzzardo requested changes
It's a great addition, because it describes a tricky detail. Thanks for the contribution.

2020-10-30 16:38 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +We can configure timeouts on both default and named client. OpenFeign works with two timeout parameters:
Change "both default and named client" to "both the default and the named client"

2020-10-30 16:38 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +NOTE: In case the server is not even running or available at all a packet results in _connection refused_. The communication ends either with an error message or in a fallback. This can happen _befor
Delete "even" and "at all"

Change "such delay" to "this delay"

2020-10-30 16:38 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +When Hystrix <<spring-cloud-openfeign#spring-cloud-feign-hystrix,is enabled>> its timeout configuration link:https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutIn
Change to:

When Hystrix <<spring-cloud-openfeign#spring-cloud-feign-hystrix,is enabled>>, its timeout configuration link:https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds[defaults] to 1000 milliseconds. Hence, it might occur before the client timeout that we configured earlier. Increasing this timeout prevents it from happening.

2020-10-30 16:38 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +NOTE: When Hystrix timeout is enabled and its timeout is set longer than of a feign client, `HystrixTimeoutException` wraps a feign exception. Otherwise, the only difference is the cause exception. T
Change to:

NOTE: When the Hystrix timeout is enabled and its timeout is set longer than that of a feign client, `HystrixTimeoutException` wraps a feign exception. Otherwise, the only difference is the cause of the exception. The purpose of `HystrixTimeoutException` is to wrap any runtime exception that occurs as first and throw an instance of itself.

2020-10-30 21:47 UTC, Nikolas-Charalambidis commented
@Buzzardo Thank you for the assistance. I have submitted the changes and marked your notes as resolved. I am sorry, I am not English native.

2020-10-30 22:23 UTC, Buzzardo requested changes

2020-10-30 22:23 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +NOTE: When the Hystrix timeout is enabled and its timeout is set longer than that of a feign client, `HystrixTimeoutException` wraps a feign exception. Otherwise, the only difference is the cause of
Remove "as" from "as first"

Sorry I missed it the first time.

2020-10-30 22:26 UTC, Nikolas-Charalambidis commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +NOTE: When the Hystrix timeout is enabled and its timeout is set longer than that of a feign client, `HystrixTimeoutException` wraps a feign exception. Otherwise, the only difference is the cause of
"...that occurs first and throw an instance of itself." or " that occurs first and **to** throw an instance of itself."? (I won't commit the bold text).

2020-11-02 13:10 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +NOTE: When the Hystrix timeout is enabled and its timeout is set longer than that of a feign client, `HystrixTimeoutException` wraps a feign exception. Otherwise, the only difference is the cause of
Lookd good the way it is now.

2020-11-02 13:10 UTC, OlgaMaciaszek approved these changes

2020-11-02 13:10 UTC, merged