Move Spring Data Jackson Modules from FeignClientsConfiguration to Fe…
spring-cloud/spring-cloud-openfeign pull request #430
Opened 2020-11-16 19:25 UTC by nkonev

…ignAutoConfiguration - Fix https://github.com/spring-cloud/spring-cloud-openfeign/issues/205

ping @OlgaMaciaszek

2020-11-24 08:01 UTC, nkonev commented
Any chance to be reviewed ?

2020-12-08 17:29 UTC, OlgaMaciaszek requested changes
Hi, @nkonev Thanks for the PR. Have added some comments. Please have a look.

2020-12-08 17:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@Bean
Let's add `@ConditionalOnMissingBean` as well.

2020-12-08 17:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@Bean
Let's add `@ConditionalOnMissingBean` as well.

2020-12-08 19:03 UTC, nkonev commented
@OlgaMaciaszek Hi, thank you, I've done.

2020-12-25 08:52 UTC, nkonev commented
@OlgaMaciaszek Hello! Do I have any chance to be reviewed/merged ?
This change looks simple, it isn't a big refactoring.

2021-01-21 12:28 UTC, OlgaMaciaszek commented
Hi, @nkonev Sorry, I was away. Let me have a look at it now.

2021-01-21 13:57 UTC, OlgaMaciaszek commented
@nkonev Have done some tests on it. This does solve the issue. However, I've realised the conditional will not be enough, as users might also register their modules just with with `Module` type also we could possibly have bean naming clashes. In order to avoid any backwards compatibility issue, let's make it opt-in by adding a new property, for example, `feign.autoconfiguration.jackson.enabled` and add a `@ConditionalOnProperty` `havingValue` `true`.

2021-01-21 17:56 UTC, nkonev commented
@OlgaMaciaszek  Thank you for reply.
Backward compatibility is pain.
I think to add it with TODO to change it in the future Spring Clod 2021 release.

2021-01-22 16:14 UTC, OlgaMaciaszek requested changes
Have added comments. Please add changes. Also, please add documentation in `spring-cloud-openfeign.adoc` describing the feature and the new property.

2021-01-22 16:14 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@ConditionalOnProperty(value = "feign.autoconfiguration.jackson.enabled", havingValue = "true", matchIfMissing = true)
Since we want it to be opt-in, it should be `matchIfMissing` = `false`, which probably is the default.

2021-01-22 16:14 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@ConditionalOnProperty(value = "feign.autoconfiguration.jackson.enabled", havingValue = "true", matchIfMissing = true)
Since we want it to be opt-in, it should be `matchIfMissing` = `false`, which probably is the default.

2021-01-22 16:29 UTC, nkonev commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@ConditionalOnProperty(value = "feign.autoconfiguration.jackson.enabled", havingValue = "true", matchIfMissing = true)
So that way we will preserve old behavior, and in order to fix bug user should manually set feign.autoconfiguration.jackson.enabled=true. Is it real need to preserve old buggy behavior ?

2021-01-22 16:36 UTC, nkonev commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@ConditionalOnProperty(value = "feign.autoconfiguration.jackson.enabled", havingValue = "true", matchIfMissing = true)
Or may be it has the meaning to do matchIfMissing=false with TODO Change in Spring Cloud 2021 ?

2021-01-26 08:23 UTC, OlgaMaciaszek approved these changes

2021-01-26 08:23 UTC, merged

2021-01-26 09:17 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@ConditionalOnProperty(value = "feign.autoconfiguration.jackson.enabled", havingValue = "true", matchIfMissing = true)
We could do it in a major. Unfortunately, a major has been just released, so we need to wait for the next one.