Lazy openfeign bean registration
spring-cloud/spring-cloud-openfeign pull request #455
Opened 2021-01-12 13:20 UTC by marcingrzejszczak

without this change we're eagerly resolving placeholder properties in passed URLs / names. Since this happens at bean definition level it's extremely early e.g. Spring Cloud Contract has not yet registered any placeholders that Feign could try to consume.
with this change we're changing the bean to become lazy initialized and we resolve the placeholder values at runtime - as late as possible.

problems:
- one of the tests uses the factory bean - there's no more factory bean since the instance supplier for the bean registration acts as one

related issue https://github.com/spring-cloud/spring-cloud-contract/issues/1303

2021-01-12 14:18 UTC, ryanjbaxter approved these changes

2021-01-12 14:26 UTC, OlgaMaciaszek requested changes
Looks good, however, I don't think it makes sense to ignore the test unless we have a plan in place to makes changes to it. We should either modify this one or create a new one or, if that's not possible, remove the existing one.

2021-01-12 20:54 UTC, spencergibb commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingConfigurerTest.java
> +@Ignore("I don't know how to test this since the factory bean is no longer created")
Why is the factory bean no longer created?

2021-01-12 21:08 UTC, lukasz-gryzbon commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingConfigurerTest.java
> +@Ignore("I don't know how to test this since the factory bean is no longer created")
From the initial PR comment: `there's no more factory bean since the instance supplier for the bean registration acts as one`

2021-01-12 21:16 UTC, spencergibb commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingConfigurerTest.java
> +@Ignore("I don't know how to test this since the factory bean is no longer created")
Then that class should be removed and the test removed.

2021-01-13 09:15 UTC, merged

2021-01-13 11:28 UTC, OlgaMaciaszek reviewed
LGTM

2021-01-14 08:47 UTC, michaldo commented
I would like you consider https://github.com/spring-cloud/spring-cloud-openfeign/issues/443

> I guess the reason is that FeignClientFactoryBean does not extend AbstractFactoryBean

Probably reusing AbstractFactoryBean patterns will decrease chance Spring-related problems

2021-01-14 09:10 UTC, marcingrzejszczak commented
But we no longer register `FeignClientFactoryBean` as a bean. Can you check @michaldo if with this change the problem in #443 didn't go away?

2021-01-15 21:35 UTC, michaldo commented
#443 still exists on 3.0.1-SNAPSHOT

It looks very suspicious to me that AbstractFactoryBean#getObject returns *"early singleton proxy"* and FeignClientFactoryBean#getObject returns *"concrete bean"*. There must be a reason that base Spring class returns proxy

2021-01-20 13:46 UTC, OlgaMaciaszek commented
Fixes gh-441.