Initial draft for micrometer support, see gh-457
spring-cloud/spring-cloud-openfeign pull request #462
Opened 2021-01-18 05:58 UTC by jonatan-ivanov

Draft PR to star discussion about #457. 
The scope of the PR is a little wider than just setting up micrometer for Feign, it makes spring-cloud-openfeign capable of configuring any [Capability](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Capability.java) (e.g.: [Metrics5Capability](https://github.com/OpenFeign/feign/blob/master/dropwizard-metrics5/src/main/java/feign/metrics5/Metrics5Capability.java) for Dropwizard Metrics or [MicrometerCapability](https://github.com/OpenFeign/feign/blob/master/micrometer/src/main/java/feign/micrometer/MicrometerCapability.java) for micrometer).

It also autoconfigures [MicrometerCapability](https://github.com/OpenFeign/feign/blob/master/micrometer/src/main/java/feign/micrometer/MicrometerCapability.java) if a `MeterRegistry` is configured and `feign-micrometer` is on the classpath.

Also, this PR is not complete, a few things are missing, I'm going to fix/add them after we agreed on the details below this section:
- Fixing current tests (some of them are failing)
- Adding new tests
- Adding docs
- Adding `@ConfigurationProperties` for the enabled flag

Topics to discuss:
- What do you think about the changes in general?
- On what level should the enabled flag be (client level can be more complicated)?
- CheckStyle messes up the formatting (see: Stream API, it should be one op/line)
- Fyi: capabilities are sorted right now but they are decorators so they should be

2021-01-19 03:53 UTC, shakuzen approved these changes
I'm not very familiar with Feign-related things, so my review is a bit limited, but auto-configuring the `MicrometerCapability` when the feign-micrometer dependency is on the classpath makes sense to me.

2021-01-19 14:37 UTC, ryanjbaxter commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java
> +	private MeterRegistry meterRegistry;
Why not add this as a variable to the bean method?

2021-01-21 03:46 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java
> +	private MeterRegistry meterRegistry;
Only to be consistent with the rest. I wanted this as a method parameter in the first place too, but other optional instances are wired this way.

2021-01-21 03:51 UTC, jonatan-ivanov commented
@ryanjbaxter
>Not sure what you mean by the level of the enable flag...

Basically the place of the flag, right now it is `feign.metrics.enabled`. So it turns metrics on/off for every client but it also could be at the client level so it turns metrics on/off per client `feign.client.config.foo.metrics.enabled`.

2021-01-21 14:19 UTC, ryanjbaxter commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java
> +	private MeterRegistry meterRegistry;
In my opinion its better to use best practices rather than being consistent.  I would be fine if you added it as a method parameter.

2021-01-21 14:20 UTC, ryanjbaxter commented
Ah OK I see.  If you can enable both use cases, that would be ideal I think.

2021-01-22 00:46 UTC, jonatan-ivanov commented
I added config for both use cases.

2021-01-22 01:11 UTC, ryanjbaxter approved these changes
Looks good, just need some docs :)

2021-01-22 01:36 UTC, jonatan-ivanov commented
@ryanjbaxter yepp, see the list in the description, I'm going to fix the current tests (the new Capability breaks reflection hacks in tests), add new ones and also docs.

2021-01-22 02:09 UTC, spencergibb requested changes
LGTM, a few minor changes.

2021-01-22 02:09 UTC, spencergibb commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +	public static class FeignClientMetricsConfiguration {
just `Metrics`.

2021-01-22 02:09 UTC, spencergibb commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientMetricsEnabledCondition.java
> +		return Optional.ofNullable(feignClientProperties).map(FeignClientProperties::getConfig)
We don't use Optional as if statements.

2021-01-22 02:09 UTC, spencergibb commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java
> +	public Capability micrometerCapability(MeterRegistry meterRegistry) {
return `MicrometerCapability`

2021-01-22 02:09 UTC, spencergibb commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java
> +	@ConditionalOnMissingBean(type = "feign.micrometer.MicrometerCapability")
No need for `type` if `MicrometerCapability` used as return type below.

2021-01-22 03:09 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +	public static class FeignClientMetricsConfiguration {
done

2021-01-22 03:13 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java
> +	public Capability micrometerCapability(MeterRegistry meterRegistry) {
Since `feign-metrics` is an optional dependency and the users might not have it on their classpath, returning `MicrometerCapability` will end up in `ClassNotFoundException`.  `Capability` is in `feign-core`, we can safely depend on it.

2021-01-22 03:31 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientMetricsEnabledCondition.java
> +		return Optional.ofNullable(feignClientProperties).map(FeignClientProperties::getConfig)
I guess there were lots of discussions around this in the past so I have no idea what am I walking into, but can I risk a question? :)

Where should we use `Optional` (other than returning it)?
If `map` qualifies as if statement I guess `filter` and `flatMap` does too as well as the `is*`, `if*`, `or`, `*else*` methods. In Java 8, that basically it, there is nothing really else in `Optional`. So not using `Optional` as if statements means not using `Optional` other than returning it (to me). Is there any other use-case where we should use it?

Btw I would ban the `isPresent`/`isEmpty`/`get` methods from this class.
Also, we might want to fix [this](https://github.com/spring-cloud/spring-cloud-openfeign/blob/582e4c0175390e0937d246eb0a2516ab00c24ac9/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignUtils.java#L58)

I'm not arguing/trolling, I'm going to fix this I just genuinely would like to understand what are the valid use-cases for `Optional` (to me this one is valid but I'm from a very small village 😄).

2021-01-22 04:19 UTC, spencergibb commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientMetricsEnabledCondition.java
> +		return Optional.ofNullable(feignClientProperties).map(FeignClientProperties::getConfig)
https://youtu.be/fBYhtvY19xA

Yeah, those should be cleaned up

2021-01-22 04:23 UTC, spencergibb commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java
> +	public Capability micrometerCapability(MeterRegistry meterRegistry) {
If it were in a static inner class there wouldn't be an issue, didn't take into account it was just a bean method

2021-01-23 01:21 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientMetricsEnabledCondition.java
> +		return Optional.ofNullable(feignClientProperties).map(FeignClientProperties::getConfig)
done (will watch the dr. deprecator talk over the weekend 🙂)

2021-01-23 01:21 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java
> +	public Capability micrometerCapability(MeterRegistry meterRegistry) {
done

2021-01-23 01:22 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java
> +	@ConditionalOnMissingBean(type = "feign.micrometer.MicrometerCapability")
done

2021-01-26 03:55 UTC, jonatan-ivanov commented
@ryanjbaxter @spencergibb I think I'm mostly done, there is at least one more thing I want to fix: I'm not able to generate docs, I suppose it's `mvn clean install -P docs -pl docs -DskipTests` but it is failing on master (and I guess this should update the `_configprops.adoc` file too).

2021-01-26 19:58 UTC, spencergibb commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +                .addCapability(micrometerCapability)
There's some formatting here. we use tabs

2021-01-26 19:58 UTC, spencergibb commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +                .addCapability(micrometerCapability)
well, at least be consistent with the spacing in the section of the docs which is tabs

2021-01-26 19:58 UTC, spencergibb commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +                .addCapability(micrometerCapability)
switch to tabs here to be consistent.

2021-01-26 20:00 UTC, spencergibb commented on spring-cloud-openfeign-core/pom.xml
> +			<groupId>nl.jqno.equalsverifier</groupId>
Unsure of introducing a new test facility that I've not heard of before just to test equals and hashcode.

2021-01-26 21:07 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +                .addCapability(micrometerCapability)
Nice catch, thanks.
It seems IntelliJ does not respect `.editorconfig` for `.adoc` files so there were quite a few lines indented using spaces, I fixed them. (Seems like a bug our `.editorconfig` does not have anything special for `.adoc`).

2021-01-26 21:24 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/pom.xml
> +			<groupId>nl.jqno.equalsverifier</groupId>
It went GA 10 years ago, it has some GH stars, not extremely popular but it seems actively maintained. I think it is useful, it just verifies whether the contracts of the equals and hashCode methods are met.

I can remove it and add some hand-written tests, what do you think?

2021-01-26 22:22 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +                .addCapability(micrometerCapability)
done, see: https://github.com/spring-cloud/spring-cloud-openfeign/pull/462#discussion_r564833160

2021-01-28 17:07 UTC, spencergibb commented on spring-cloud-openfeign-core/pom.xml
> +			<groupId>nl.jqno.equalsverifier</groupId>
I'd rather remove it. Are the tests really necessary?

2021-01-28 17:22 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/pom.xml
> +			<groupId>nl.jqno.equalsverifier</groupId>
Removed the lib and the tests too, codecov is not entirely happy, I think it is also nice to cover them, I'm going to write a few tests.

2021-01-28 20:15 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/pom.xml
> +			<groupId>nl.jqno.equalsverifier</groupId>
@spencergibb I think it's done

2021-02-01 23:48 UTC, spencergibb approved these changes
Apart from one class rename, LGTM

2021-02-01 23:48 UTC, spencergibb commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +	public static class MetricsConfiguration {
`Configuration` is typically for spring configuration or autoconfiguration. How about `MetricsProperties` with the field stating `metrics`?

2021-02-01 23:48 UTC, spencergibb commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientErrorDecoderTests.java
> +		Object invocationHandler = ReflectionTestUtils.getField(invocationHandlerLambda, "arg$2");
This looks brittle. No need to do anything with it now, but we should think about how (if?) we can fix it later.

2021-02-03 01:48 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +	public static class MetricsConfiguration {
Done. Fyi: we might want to fix `FeignClientConfiguration` too.

2021-02-03 01:50 UTC, jonatan-ivanov commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientErrorDecoderTests.java
> +		Object invocationHandler = ReflectionTestUtils.getField(invocationHandlerLambda, "arg$2");
Agree.

2021-02-08 18:18 UTC, spencergibb commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +	public static class MetricsConfiguration {
Looks good!

2021-02-09 11:09 UTC, OlgaMaciaszek approved these changes
The feature implementation looks very good. Thanks for adding extensive tests. Have added a comment about some cosmetic formatting changes, though.

2021-02-09 11:15 UTC, OlgaMaciaszek commented
Let's wait with the merge, though, till @Buzzardo reviews the doc changes.

2021-02-09 14:49 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> -    public static void main(String[] args) {
This is an interesting issue, it seems IntelliJ's editorconfig plugin did not respect the .editorconfig file everywhere (it seems they have fixed this since tehn) so when I edited this file, my indentations were spaces that was noticed by Spencer: https://github.com/spring-cloud/spring-cloud-openfeign/pull/462#discussion_r564793286

This issue presents everywhere in this file, the indentation is pretty mixed so I fixed it everywhere. I assume we don't want any file to have mixed indentation, so my question is can we fix it in this PR or shall I open a new one?

2021-02-09 16:03 UTC, Buzzardo requested changes

2021-02-09 16:03 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +* `MeterRegistry` bean is available
Change to: 

* A `MeterRegistry` bean is available

2021-02-09 16:03 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +If you want to enable/disable merics per client, simply don't set `feign.metrics.enabled` and use `feign.client.config.feignName.metrics.enabled`.
Change "enable/disable" to "enable or disable"

Remove "simply" (always) and change "don't" to "do not" (always).

2021-02-09 18:50 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +* `Capability` (`MicrometerCapability` is provided by default, see above)
It refers to `MicrometerCapability` in the previous list in this section that I can't link but I removed the "see above" part, I think this makes sense without it.

2021-02-09 18:51 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +* `MicrometerCapability` micrometerCapability: if `feign-micrometer` is on the classpath and `MeterRegistry` is available
done

2021-02-09 18:52 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +* `Client` feignClient: if Spring Cloud LoadBalancer is on the classpath, `FeignBlockingLoadBalancerClient` is used.
done

2021-02-09 18:55 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +Capabilities expose core Feign components so that these components can be modified, e.g.: Capabilities can take the `Client`, _decorate_ it, and give the decorated instance back to Feign.
done

2021-02-09 18:56 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +Support for metrics libraries is a good real-life example for this, see <<feign-metrics>>.
done

2021-02-09 18:56 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +Creating one or more `Capability` beans and placing them in a `@FeignClient` configuration allows you to register them and modify the behavior of the involved client.
done

2021-02-09 18:58 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +If all of the following conditions are true, a `MicrometerCapability` bean is created and registered so that your Feign client will publish metrics to Micrometer:
done

2021-02-09 18:58 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +* `MeterRegistry` bean is available
done

2021-02-09 19:00 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +If you want to enable/disable merics per client, simply don't set `feign.metrics.enabled` and use `feign.client.config.feignName.metrics.enabled`.
done

2021-02-09 19:05 UTC, jonatan-ivanov commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> -    public static void main(String[] args) {
fyi: I talked to Olga, she's ok with leaving the indentation fixes in this PR.

2021-02-09 19:13 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +* `Capability` (`MicrometerCapability` is provided by default, see above)
Since it's that close, OK.

2021-02-09 19:14 UTC, Buzzardo approved these changes

2021-02-09 19:58 UTC, merged