Encode Pageable.Sort with percent encoded comma. Fixes gh-440.
spring-cloud/spring-cloud-openfeign pull request #467
Opened 2021-01-23 05:13 UTC by KENNYSOFT

I've modified https://github.com/spring-cloud/spring-cloud-openfeign/blob/faff6aef8acdf2367c1b5596a384cbe86e1200c5/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringEncoder.java as suggested in #440 along with corresponding tests.

If you run tests which I add without the patch of `PageSpringEncoder.java` and you'll be able to see the test fails.

2021-01-23 05:13 UTC, pivotal-issuemaster commented
@KENNYSOFT Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=467)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=467) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-01-23 05:15 UTC, pivotal-issuemaster commented
@KENNYSOFT Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=467)!

2021-02-08 14:05 UTC, OlgaMaciaszek commented
Fixes gh-440.

2021-02-08 14:55 UTC, nkonev commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		if (!orderList.isEmpty()) {
I'd rewritten it as
`assertThat(orderList.getSize()).isEqualTo(2);`

2021-02-08 14:57 UTC, nkonev commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		if (optionalOrder.isPresent()) {
I'd rewritten it as
`assertThat(optionalOrder.isPresent()).isTrue();`

2021-02-08 15:34 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		if (optionalOrder.isPresent()) {
Actually it's guaranteed because we asserted that `...getSort()` has size 1.

2021-02-08 15:52 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		if (optionalOrder.isPresent()) {
But yeah changed. 86785dca3fd11a8f4d299058e5b9174a807cb125

2021-02-08 15:52 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		if (!orderList.isEmpty()) {
Resolved in 86785dca3fd11a8f4d299058e5b9174a807cb125

2021-02-08 15:52 UTC, nkonev approved these changes

2021-02-08 17:01 UTC, OlgaMaciaszek requested changes
@KENNYSOFT Other than some minor formatting issues, the PR looks good. However, similarly as with the previous one, please submit it against `2.2.x` so that the changes are included in the `Hoxton` release train as well.

2021-02-08 17:01 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +
Please remove the unnecessary empty line.

2021-02-08 17:01 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +
Please remove the unnecessary empty line.

2021-02-08 17:01 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +
Please remove the unnecessary empty line.

2021-02-08 17:01 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +
Please remove the unnecessary empty line.

2021-02-08 17:21 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		if (!orderList.isEmpty()) {
Since it's rebased, now in c08b8733345e90d1785e042617a844fd13010272

2021-02-08 17:21 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		if (optionalOrder.isPresent()) {
Since it's rebased, now in c08b8733345e90d1785e042617a844fd13010272

2021-02-08 17:21 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +
Resolved in 364be92b65f2bae667b06fb2c08d04fa05643bde

2021-02-08 17:21 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +
Resolved in 364be92b65f2bae667b06fb2c08d04fa05643bde

2021-02-08 17:21 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +
Resolved in 364be92b65f2bae667b06fb2c08d04fa05643bde

2021-02-08 17:30 UTC, KENNYSOFT commented
Test fails as well but I saw the comments 🙃

https://github.com/spring-cloud/spring-cloud-openfeign/blob/f6cf14f257bf521f9af3a751f348270af4eca9a0/spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/ribbon/FeignRibbonClientRetryTests.java#L83-L84

2021-02-08 17:31 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +
Resolved in 364be92b65f2bae667b06fb2c08d04fa05643bde

2021-02-08 17:33 UTC, OlgaMaciaszek approved these changes
LGTM.

2021-02-08 17:33 UTC, merged