Add apahce hc5 async
spring-cloud/spring-cloud-openfeign pull request #488
Opened 2021-02-20 17:00 UTC by thanhj

[WIP] Add apahce hc5 async
[TODO]
- Add ApacheAsyncHttpClientConnectionManagerFactory to Spring-cloud-common
- Add ApacheAsyncHttpClientFactory to Spring-cloud-common
- Unit-test
- Other stuff

2021-02-24 09:34 UTC, thanhj commented
@OlgaMaciaszek, I have tested this implementation but it did not work. I am also not sure how to write unit-test for this one, may you have some suggestions?

2021-02-25 14:23 UTC, thanhj commented
@OlgaMaciaszek, I removed AsyncHttpClient5 from this PR's scope, as it is kind of complicated to do now for me. 
Please help to review the PR.

2021-02-25 14:36 UTC, OlgaMaciaszek commented
> @OlgaMaciaszek, I have tested this implementation but it did not work.

You mean the async implementation did not work?

2021-02-25 14:45 UTC, OlgaMaciaszek requested changes
@thanhj, thanks for submitting the PR. In general, it looks good, but have added some comments. Please address.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +			return HttpClient5FeignConfigurationHelper.connectionManager(httpClientProperties);
Due to issues with `HttpClientConnectionManager` we use a [timer to close expired connections](https://github.com/spring-cloud/spring-cloud-openfeign/blob/1dbf9c2d6c00825363a144feb8c4d157bb26d60e/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java#L181-L187). Is this handled better by hc5?

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +			return AsyncHttpClient5FeignConfigurationHelper.connectionManager(httpClientProperties);
Due to issues with `HttpClientConnectionManager` we use a [timer to close expired connections](https://github.com/spring-cloud/spring-cloud-openfeign/blob/1dbf9c2d6c00825363a144feb8c4d157bb26d60e/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java#L181-L187). Is this handled better by hc5?

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +			AsyncHttpClient5FeignConfigurationHelper.destroy(this.asyncHttpClient5);
Please remove any unnecessary use of `this` in this and other classes.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/AsyncHttpClient5FeignConfiguration.java
> + * Copyright 2013-2020 the original author or authors.
2013-2021

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +		public AsyncClient feignClient(CloseableHttpAsyncClient httpAsyncClient) {
Why not `AsyncClient<HttpClientContext>`?

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/AsyncHttpClient5FeignConfiguration.java
> +	public AsyncClient feignClient(CloseableHttpAsyncClient httpAsyncClient) {
Why not `AsyncClient<HttpClientContext>`?

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/AsyncHttpClient5FeignConfiguration.java
> +		this.asyncHttpClient5 = AsyncHttpClient5FeignConfigurationHelper.httpClient(connectionManager,
Please remove any unnecessary use of `this` in this and other classes.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/AsyncHttpClient5FeignConfiguration.java
> +		AsyncHttpClient5FeignConfigurationHelper.destroy(this.asyncHttpClient5);
Please remove any unnecessary use of `this` in this and other classes.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/AsyncHttpClient5FeignConfiguration.java
> +		return AsyncHttpClient5FeignConfigurationHelper.connectionManager(httpClientProperties);
Due to issues with HttpClientConnectionManager we use a timer to close expired connections. Is this handled better by hc5?

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/AsyncHttpClient5FeignConfigurationHelper.java
> + * Copyright 2013-2020 the original author or authors.
2013-2021

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@Configuration(proxyBeanMethods = false)
Please add your name with the `@author` tag to the javadoc.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/AsyncHttpClient5FeignConfigurationHelper.java
> + * @author Nguyen Ky Thanh
Please add a line of class description to the javadoc.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java
> + * Copyright 2013-2020 the original author or authors.
2013-2021

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfigurationHelper.java
> + * Copyright 2013-2020 the original author or authors.
2013-2021.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfigurationHelper.java
> + * @author Nguyen Ky Thanh
Please add a line of class description to the javadoc.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java
> +	/**
Let's move the properties that only apply to Apache HC5 to another object in this class, so that we get `feign.httpclient.hc5.xxx` property naming.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> + * Copyright 2013-2020 the original author or authors.
2013-2021

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +@RunWith(ModifiedClassPathRunner.class)
We try to use `junit.jupiter` for any new tests. Could you please switch to it?

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +			this.httpClient5 = HttpClient5FeignConfigurationHelper.httpClient(connectionManager, httpClientProperties);
Please remove unnecessary use of `this.` in this and other classes.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java
> +		HttpClient5FeignConfigurationHelper.destroy(this.httpClient5);
Please remove unnecessary use of `this.` in this and other classes.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +				.properties("debug=true", "feign.httpclient5.enabled=true", "feign.httpclient.enabled=false")
why `"debug=true"`?

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +		if (this.context != null) {
Please remove unnecessary use of `this.` in this and other classes.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +		CloseableHttpClient httpClient = this.context.getBean(CloseableHttpClient.class);
Please remove unnecessary use of `this.` in this and other classes.

2021-02-25 14:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +	public void noMoreHttpClient4Instances() throws Exception {
Let's verify the opposite scenario as well (in this or a different test class) that when hc5 is not on classpath or it is disabled while HttpClient 4 is on classpath, the latter will be used.

2021-02-25 14:53 UTC, OlgaMaciaszek commented
Fixes gh-486.

2021-02-25 22:38 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +			return HttpClient5FeignConfigurationHelper.connectionManager(httpClientProperties);
The new ConnectionPool provide a new option for optimizing the timeout issue:
`public enum PoolReusePolicy {
    /**
     * Re-use as few connections as possible making it possible for connections to become idle and expire.
     */
    LIFO,

    /**
     * Re-use all connections equally preventing them from becoming idle and expiring.
     */
    FIFO

}`

 It may not solve the problem you mentioned properly but I'd rather not use the timer for now.

2021-02-26 00:10 UTC, thanhj commented
> > @OlgaMaciaszek, I have tested this implementation but it did not work.
> 
> @thanhj You mean the async implementation did not work?

The current FeignClientFactoryBean is tightly coupled to Feign.Builder(), but the async flow require AsyncFeign.<>asyncBuilder(). It would be more time to implement the async flow, do you have any suggestions? Or how to restructure FeignClientFactoryBean and its related classes?

2021-02-26 00:11 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +		CloseableHttpClient httpClient = this.context.getBean(CloseableHttpClient.class);
Done!

2021-02-26 00:11 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +		if (this.context != null) {
Done

2021-02-26 00:11 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +				.properties("debug=true", "feign.httpclient5.enabled=true", "feign.httpclient.enabled=false")
Removed.

2021-02-26 00:11 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java
> +		HttpClient5FeignConfigurationHelper.destroy(this.httpClient5);
Done!

2021-02-26 00:12 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +		public AsyncClient feignClient(CloseableHttpAsyncClient httpAsyncClient) {
Updated.

2021-02-26 00:12 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/AsyncHttpClient5FeignConfiguration.java
> + * Copyright 2013-2020 the original author or authors.
Updated.

2021-02-26 00:12 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +			AsyncHttpClient5FeignConfigurationHelper.destroy(this.asyncHttpClient5);
Updated.

2021-02-26 00:13 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +			return AsyncHttpClient5FeignConfigurationHelper.connectionManager(httpClientProperties);
Refer my reply to a similar comment.

2021-02-26 11:42 UTC, OlgaMaciaszek commented
> I have added back the AsyncHc5AutoConfig, but it is still far from the final.

@thanhj Please either remove whatever is not ready for review and work on it in a different branch/PR or close this PR when all parts of it are ready for review from our side.

2021-02-26 16:01 UTC, thanhj commented
> > I have added back the AsyncHc5AutoConfig, but it is still far from the final.
> 
> @thanhj Please either remove whatever is not ready for review and work on it in a different branch/PR or close this PR when all parts of it are ready for review from our side.

I will close this PR and open another PR to branch 2.2.x with completed changes.

2021-02-26 16:12 UTC, closed without merging

2021-03-01 09:13 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +	public void noMoreHttpClient4Instances() throws Exception {
Done

2023-03-26 20:25 UTC, thanhj commented
Hi @OlgaMaciaszek, thanks for letting me know. Unfortunately, my current workload doesn't allow me to contribute on this feature.

2023-03-27 11:15 UTC, OlgaMaciaszek commented
Hi @thanhj, thanks for the update and for your previous contributions.