mentioning Feign instead of Sleuth
spring-cloud/spring-cloud-openfeign pull request #495
Opened 2021-02-25 18:44 UTC by xkrishnam

In The last line in Feign's reference docs Sleuth mentioned instead of Feign. I have corrected this very very small mistake.

2021-02-25 18:44 UTC, pivotal-issuemaster commented
@xkrishnam Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=495)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=495) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-02-25 18:45 UTC, pivotal-issuemaster commented
@xkrishnam Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=495)!

2021-02-26 16:20 UTC, OlgaMaciaszek requested changes
@xkrishnam Thanks, for spotting this. Please address the comment. Also, this bug exists in the `Hoxton` release train as well. Therefore, could you submit the change against the `2.2.x` branch instead of `master`?

2021-02-26 16:20 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +To see the list of all Feign related configuration properties please check link:appendix.html[the Appendix page].
Let's change from "Feign" to "Spring Cloud OpenFeign".

2021-02-26 17:17 UTC, xkrishnam commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +To see the list of all Feign related configuration properties please check link:appendix.html[the Appendix page].
Done as suggested and opening PR against 2.2.x too

2021-02-26 17:22 UTC, OlgaMaciaszek commented
Thanks @xkrishnam . https://github.com/spring-cloud/spring-cloud-openfeign/pull/497.

2021-02-26 17:22 UTC, closed without merging