Add Apache HC5 client option
spring-cloud/spring-cloud-openfeign pull request #498
Opened 2021-02-27 23:02 UTC by thanhj

2021-02-27 23:06 UTC, thanhj commented
Hi @OlgaMaciaszek,
I re-summitted this PR regarding https://github.com/spring-cloud/spring-cloud-openfeign/pull/488.
Please review, thanks.

2021-03-03 16:29 UTC, OlgaMaciaszek requested changes
@thanhj , thanks for submitting this. I have added some comments that should be addressed. Also, thanks for adding Ribbon-backed load-balanced setup, but Spring Cloud LoadBalancer-backed one is still missing. (see https://github.com/spring-cloud/spring-cloud-openfeign/blob/2.2.x/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/HttpClientFeignLoadBalancerConfiguration.java and https://github.com/spring-cloud/spring-cloud-openfeign/blob/2.2.x/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/HttpClientFeignLoadBalancerConfiguration.java as a reference).

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@ConditionalOnProperty({ "feign.httpclient.hc5.enabled" })
Let's add `havingValue="true"`; let's remove list brackets since it's only one property.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@ConditionalOnProperty({ "feign.httpclient.hc5.enabled" })
This configuration should be for non-load-balanced cases. So it should have conditionals on a missing Netflix LoadBalancer and Spring Cloud LoadBalnacer classes.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/HttpClient5FeignLoadBalancedConfiguration.java
> + * @author Nguyen Ky Thanh
Please add a class description line.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/HttpClient5FeignLoadBalancedConfiguration.java
> +@ConditionalOnProperty("feign.httpclient.hc5.enabled")
Let's add `havingValue="true"`.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/HttpClient5FeignLoadBalancedConfiguration.java
> +	@ConditionalOnMissingBean(Client.class)
You already have a client being created in the imported configuration: https://github.com/thanhj/spring-cloud-openfeign/blob/0fbe617bbcdbeec6436bb9aef7abbd2fecfc078e/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java#L107-L111, so I would assume this condition might not be fulfilled even when we want to create a load-balanced client. Please verify.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java
Please add a javadoc description for property field.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java
> +		private PoolConcurrencyPolicy poolConcurrencyPolicy = DEFAULT_POOL_CONCURRENCY_POLICY;
Please add a javadoc description for property field.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java
> +		private PoolReusePolicy poolReusePolicy = DEFAULT_POOL_REUSE_POLICY;
Please add a javadoc description for property field.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +@ExtendWith({ SpringExtension.class })
Pleas remove unnecessary list brackets from annotation.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +public class FeignHttpClient5ConfigurationTests {
Please remove unnecessary `public` qualifier.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +	public void verifyHttpClient5AutoConfig() {
Please remove unnecessary `public` qualifier.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +	public void hc5ShouldWinIfTheBothVersionsAvailable() {
Please remove unnecessary `public` qualifier.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/ribbon/FeignRibbonHttpClient5ConfigurationTests.java
> +				this.connectionManager);
Please remove unnecessary `this.` keywords from this class.

2021-03-03 16:29 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/ribbon/FeignRibbonHttpClient5ConfigurationTests.java
> +public class FeignRibbonHttpClient5ConfigurationTests {
Let's add a test verifying that the right load-balanced Http5 backed Feign Client is created when either Ribbon or SC LoadBalancer.

2021-03-03 16:41 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +	public void hc5ShouldWinIfTheBothVersionsAvailable() {
Let's verify the opposite scenario as well (in this or a different test class) that when hc5 is not on classpath or it is disabled while HttpClient 4 is on classpath, the latter will be used.

2021-03-03 22:48 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@ConditionalOnProperty({ "feign.httpclient.hc5.enabled" })
Done!

2021-03-03 22:49 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +	@ConditionalOnProperty({ "feign.httpclient.hc5.enabled" })
Done!

2021-03-04 09:32 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/HttpClient5FeignLoadBalancedConfiguration.java
> + * @author Nguyen Ky Thanh
Done!

2021-03-04 09:32 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/HttpClient5FeignLoadBalancedConfiguration.java
> +@ConditionalOnProperty("feign.httpclient.hc5.enabled")
Done!

2021-03-04 09:33 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/HttpClient5FeignLoadBalancedConfiguration.java
> +	@ConditionalOnMissingBean(Client.class)
You are right, I have fixed it.

2021-03-04 09:36 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +public class FeignHttpClient5ConfigurationTests {
It turned out that I couldn't find an equivalent of `@ClassPathExclusions("ribbon-loadbalancer-{version:\\d.*}.jar")` in JUnit5, so I revert the use of JUnit4 in this case.

2021-03-04 09:36 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +	public void hc5ShouldWinIfTheBothVersionsAvailable() {
Done!

2021-03-04 09:36 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/ribbon/FeignRibbonHttpClient5ConfigurationTests.java
> +				this.connectionManager);
Done!

2021-03-04 11:36 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/ribbon/FeignRibbonHttpClient5ConfigurationTests.java
> +public class FeignRibbonHttpClient5ConfigurationTests {
Done!

2021-03-04 11:38 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +	public void verifyHttpClient5AutoConfig() {
Please check my above comment for the reason to revert back to use JUnit4 in this class.

2021-03-04 11:40 UTC, thanhj commented
Thanks for your feedback and comments @OlgaMaciaszek, I have updated all of them, please have another check!

2021-03-04 12:34 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java
Im not sure this one, it is not newly added.

2021-03-09 15:06 UTC, OlgaMaciaszek requested changes
@thanhj Thanks for updating the PR. There are still some things to address. Please see the comments.

2021-03-09 15:06 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java
> +		public static final PoolConcurrencyPolicy DEFAULT_POOL_CONCURRENCY_POLICY = PoolConcurrencyPolicy.STRICT;
Sorry, have not noticed this before. You should not use Hc5-specific types in the properties (or anywhere else where we you do not verify if hc5 is on classpath before instantiating). This causes `NoClassDefFoundError` when HC5 is not on classpath. You can use your own enums or Strings and translate into HC5 types HC-5 specific classes.

Btw., to ensure feign projects run well after your changes, both with and without HC5 (you can also test with and without load-balancing to be sure), you can build locally from your branch and then try a sample (for example, [this one](https://github.com/spring-cloud-samples/feign-eureka)) against your version.

2021-03-09 22:40 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java
> +		public static final PoolConcurrencyPolicy DEFAULT_POOL_CONCURRENCY_POLICY = PoolConcurrencyPolicy.STRICT;
You are totally right, I just fixed that and added more tests accordingly.

2021-03-10 11:09 UTC, thanhj commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java
Added

2021-03-10 11:34 UTC, OlgaMaciaszek requested changes
@thanhj Thanks for adding changes (and for updating the PR in such a timely manner :)). This PR looks nearly ready now and we should be able to merge it soone, however, I have found one more inconsistent behaviour while doing some tests on it. Please see the new comment.

2021-03-10 14:56 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +		public void hc5ShouldWinIfTheBothVersionsAvailable() {
I don't really understand your comment.
Do you have an uncovered example case that really needs to involve this AnyNestedCondition?

2021-03-10 14:58 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +		public void hc5ShouldWinIfTheBothVersionsAvailable() {
This test is exactly testing the order-induced behavior. But I don't think we need to include a `HttpClient5DisabledConditions` to exiting configuration classes.

2021-03-10 23:00 UTC, thanhj commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
> +		public void hc5ShouldWinIfTheBothVersionsAvailable() {
Thanks @OlgaMaciaszek 
I have added that logic and test cases to cover that scenario, please have a look.

2021-03-11 13:12 UTC, OlgaMaciaszek approved these changes
Thanks, @thanhj . Looks good now.

2021-03-11 13:13 UTC, OlgaMaciaszek commented
Fixes gh-486.

2021-03-11 13:14 UTC, merged

2021-03-11 13:53 UTC, thanhj commented
@OlgaMaciaszek , do I need to raise another similar PR to master branch?