Supports Pageable, Sort annotated as SpringQueryMap to use with RequestBody
spring-cloud/spring-cloud-openfeign pull request #502
Opened 2021-03-04 02:59 UTC by KENNYSOFT

Based on https://github.com/spring-cloud/spring-cloud-openfeign/issues/440#issuecomment-776979189

I've implemented `PageableSpringQueryMapEncoder` which processes `Pageable`, `Sort` which annotated as `@SpringQueryMap` to use with `@RequestBody`, along with tests.

Usage:

```java
@RequestMapping(value = "invoicesPagedWithBody", method = RequestMethod.POST,
		consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
ResponseEntity<Page<Invoice>> getInvoicesPagedWithBody(
		@SpringQueryMap org.springframework.data.domain.Pageable pageable, @RequestBody String titlePrefix);
```

2021-03-09 17:13 UTC, OlgaMaciaszek commented
@KENNYSOFT thanks for submitting the PR - will review it tomorrow; yes, please submit against `2.2.x` instead of `master`.

2021-03-10 02:03 UTC, KENNYSOFT commented
Done!

2021-03-10 12:41 UTC, OlgaMaciaszek requested changes
@KENNYSOFT Thanks for creating this PR. Have added some comments about minor issues in javadocs and tests - please address. Other than that, it looks good.

2021-03-10 12:41 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +				"feign.client.config.default.loggerLevel=full",
Why full logging and debug logging in these tests?

2021-03-10 12:41 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringQueryMapEncoder.java
> + * Provides support for encoding Pageable annotated as SpringQueryMap.
Use `{@link SpringQueryMap}` in javadoc.

2021-03-10 12:41 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringQueryMapEncoder.java
> + */
Add `@since 2.2.8` to javadoc.

2021-03-10 12:41 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		assertThat(firstInvoice.getTitle()).startsWith("InvoiceTitleFromBody");
The test should verify sort has been properly passed to server.

2021-03-10 12:41 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/app/resource/InvoiceResource.java
> +		return ResponseEntity.ok(createInvoiceList(titlePrefix, 100));
`Sort` is not really used while returning results, so we can't verify if it was generated correctly.

2021-03-10 14:45 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +				"feign.client.config.default.loggerLevel=full",
To see HTTP requests during development, but yeah not necessary. Will remove.

2021-03-10 15:29 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		assertThat(firstInvoice.getTitle()).startsWith("InvoiceTitleFromBody");
Right, thanks. IT DIDN'T PASSED.

2021-03-10 15:58 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringQueryMapEncoder.java
> + */
Resolved in d5b2e44eb755158f7663375da5de487f63b76a0e

2021-03-10 15:59 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +				"feign.client.config.default.loggerLevel=full",
Resolved in c114bad369fb672835e0a41fbaeacc8159f7dfd8

2021-03-10 15:59 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
> +		assertThat(firstInvoice.getTitle()).startsWith("InvoiceTitleFromBody");
Resolved in c114bad369fb672835e0a41fbaeacc8159f7dfd8

2021-03-10 15:59 UTC, KENNYSOFT commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/app/resource/InvoiceResource.java
> +		return ResponseEntity.ok(createInvoiceList(titlePrefix, 100));
Resolved in c114bad369fb672835e0a41fbaeacc8159f7dfd8

2021-03-10 16:28 UTC, KENNYSOFT commented
Have little idea to increase coverage but seems verbose... 😕

2021-03-10 16:30 UTC, OlgaMaciaszek approved these changes
LGTM

2021-03-10 16:30 UTC, merged