GH-475: Optional Feign clients eager initializing mechanism
spring-cloud/spring-cloud-openfeign pull request #512
Opened 2021-03-14 15:21 UTC by Periecle

Pull Request majorly influenced by[ similar Ribbon feature](https://github.com/spring-cloud/spring-cloud-netflix/pull/1749), therefore API and configuration are close to each other for usability. 
Also updated documentation explaining configuration and implementation details.

2021-03-16 11:47 UTC, OlgaMaciaszek requested changes
@Periecle thanks for submitting this. Have added some comments to address, however, have also run some tests on the sample provided in the issue (https://github.com/spring-cloud/spring-cloud-openfeign/issues/475) and this does not really seem to solve the issue, so probably will require further investigation.

2021-03-16 11:47 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +			return new FeignApplicationContextInitializer(feignContext, feignEagerLoadProperties.getClients());
On a second thought, it does not seem there's a need to autowire it this way and mark as `required=false`. We could just inject it as an argument instead:
```
@Bean
		public FeignApplicationContextInitializer feignApplicationContextInitializer(FeignContext feignContext,
				FeignEagerLoadProperties feignEagerLoadProperties) {
			return new FeignApplicationContextInitializer(feignContext, feignEagerLoadProperties.getClients());
		}
```

2021-03-16 12:12 UTC, Periecle commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java
> +			return new FeignApplicationContextInitializer(feignContext, feignEagerLoadProperties.getClients());
Agree, properties can be injected this way, will do it.

2021-03-16 12:12 UTC, Periecle commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignEagerLoadProperties.java
> +	private List<String> clients;
Okay, will do

2021-03-16 12:13 UTC, Periecle commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientEagerInitializationTests.java
> +	@EnableConfigurationProperties(FeignEagerLoadProperties.class)
Reasonable. Will fix this

2021-03-16 12:22 UTC, Periecle commented
> @Periecle thanks for submitting this. Have added some comments to address, however, have also run some tests on the sample provided in the issue (#475) and this does not really seem to solve the issue, so probably will require further investigation.

Author of original issue was struggling with initialising  feign clients in async way from ForkJoinPool, you proposed to implement something similar to ribbon.eager-load mechanism. I think my PR won't fix sample from original issue, but propose options to provide such functionality directly without need for workarounds. 
On second thought, it seems that cloud-openfeign need option for initialising Ribbon LB clients with something like 
feign.ribbon.warmup. Actually, I am already working on this feature.

2021-03-28 12:36 UTC, Periecle commented
@OlgaMaciaszek, hi. Can you update me with current status of review?

2021-04-12 10:33 UTC, OlgaMaciaszek commented
> hi. Can you update me with current status of review?

@Periecle , I understood you were still working on this bit for the PR:

> On second thought, it seems that cloud-openfeign need option for initialising Ribbon LB on ApplicationReadyEvent optionally on feign.ribbon.warmup, . Actually, I am already working on this feature.

Or will you be submitting it in another PR?

2023-02-01 16:24 UTC, closed without merging