Add FeignClientBuilder.Builder#customize(FeignBuilderCustomizer) (#499)
spring-cloud/spring-cloud-openfeign pull request #515
Opened 2021-03-17 01:28 UTC by Sam-Kruglov

fixes #499

2021-03-17 01:30 UTC, Sam-Kruglov commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignBuilderCustomizerTests.java
> +	@Test
copied from above, diff 83, 84, 88, 90

2021-03-17 01:32 UTC, Sam-Kruglov commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientBuilderTests.java
> +			builder);
using IDEA style from spring-cloud-build-tools

2021-04-12 12:01 UTC, OlgaMaciaszek requested changes
@Sam-Kruglov Thanks for submitting the PR. In general, it looks good. There are a few minor issues to address - please take a look at the comments. Also, please add  your full name with `@author` tags to the javadocs of the classes you've changed. Apart from this, since this is not backwards incompatible, I'm thinking it would make sense to add it to the `2.2.x` branch instead of `master`, so that it's available in the `Hoxton` release train as well (the easiest way of doing that would probably be to cherry-pick the commits against `2.2.x` and create a new branch and PR).

2021-04-12 13:54 UTC, Sam-Kruglov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +	private List<FeignBuilderCustomizer> additionalCustomizers = new LinkedList<>();
Because we don't really need the indices here, but ok, I'll put array instead to keep things consistent.

2021-04-12 13:59 UTC, Sam-Kruglov commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientBuilder.java
> +		 * @param customizer applied in the same order as supplied here
I think this is self-explanatory but sure

2021-04-12 14:17 UTC, Sam-Kruglov commented
rerouted to 2.2.x

2021-04-12 14:36 UTC, OlgaMaciaszek requested changes
@Sam-Kruglov Thanks for adding the changes - just one small change to be made and it will be good to merge.

2021-04-12 14:36 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientBuilder.java
> +		 * @param customizer applied in the same order as supplied here
I meant sth more like `the {@link Builder} with the customizer added` rather than just `this`.

2021-04-13 10:56 UTC, OlgaMaciaszek commented
Fixes gh-499

2021-04-13 10:57 UTC, OlgaMaciaszek approved these changes
LGTM.

2021-04-13 10:57 UTC, merged