Support circuit breaker group name
spring-cloud/spring-cloud-openfeign pull request #520
Opened 2021-04-05 15:02 UTC by Ferioney

Fixes gh-514

2021-04-05 15:03 UTC, Ferioney commented
This changes required the latest version of Spring Cloud Commons

2021-04-15 10:27 UTC, OlgaMaciaszek requested changes
@Ferioney Thanks for submitting the PR. Apart from a cosmetic change (see comment), this generally looks good. However, as it would be changing existing behaviour and, thus, potentially breaking backwards compatibility for some users, it will need to be changed to an opt-in feature (for example, using a property flag), and then changed into the default behaviour in a major release.

2021-04-15 10:27 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerInvocationHandler.java
> +		CircuitBreaker circuitBreaker = this.factory.create(circuitName, this.feignClientName);
Please remove unnecessary `this.` keyword.

2021-04-15 17:09 UTC, Ferioney commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerInvocationHandler.java
> +		CircuitBreaker circuitBreaker = this.factory.create(circuitName, this.feignClientName);
Removed

2021-04-16 08:56 UTC, OlgaMaciaszek requested changes
Hi @Ferioney, thanks for updating the PR.  Just a few cosmetic changes are left to make now:
- have added a comment - please address
- please add your full name and surname with `@author` tag to the javadocs of the classes you've changed
- please add information about the new flag and feature to the documentation `spring-cloud-openfeign.adoc` in the `Feign Spring Cloud CircuitBreaker Support` section (after changing the docs rebuild with `-Pdocs` mvn flag to recreate auto-generated doc files).

2021-04-16 08:56 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerTargeter.java
> +		return builder.circuitBreakerFactory(this.circuitBreakerFactory).feignClientName(feignClientName)
Please remove unnecessary `this.` keywords.

2021-04-16 15:39 UTC, Ferioney commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerTargeter.java
> +		return builder.circuitBreakerFactory(this.circuitBreakerFactory).feignClientName(feignClientName)
Removed

2021-04-16 15:40 UTC, Ferioney commented
@OlgaMaciaszek 
- `this.` removed
- I added `@ author` tags to all changed classes (except for classes that don't have `@ author` tag)
- Documentation updated

2021-04-20 09:41 UTC, OlgaMaciaszek approved these changes
LGTM.

2021-04-20 09:41 UTC, merged