Make feign.Request.Options as refreshable beans inside This is to make Feign clients
spring-cloud/spring-cloud-openfeign pull request #526
Opened 2021-04-12 11:12 UTC by jas34

Refer: #468

- Created OptionsFactoryBean to create instance of Options bean with applicable configuration properties.
- FeignClientRegistrar:
    - created a private method to populate Bean definition for Options bean.
    - invoked private method during Feign bean definition registration phase.
- FeignClientFactoryBean:
    - updated to get refreshable options bean from feign context by bean name.
- FeignContext:
    - exposed a method to get bean from context by bean name.
- added test cases.

gh-468

2021-04-15 13:20 UTC, OlgaMaciaszek requested changes
Hello, @jas34 . Thanks for submitting the PR. I have added some comments.
Also, I have run some tests and have verified that the `Options` properties do not seem to be properly passed on to the request when `refresh-enabled` is set to `true` - please verify.
In order to reproduce, use [this sample](https://github.com/spring-cloud-samples/feign-eureka), modify the SC version to `2020.0.3-SNAPSHOT` to pick your locally built changes and update [`application.yml`](https://gist.github.com/OlgaMaciaszek/ca501419887c588edf97292138fefe7e). Then when you debug at [`Client#execute`]( https://github.com/OpenFeign/feign/blob/3ea3708cddef0d20c0bf443c18f2364c8d8df062/core/src/main/java/feign/Client.java#L104) the value set in properties is not passed on correctly, however with `refresh-enabled` set to `false` it is.

2021-04-16 10:31 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
>  	@Override
respective methods updated

2021-04-16 10:32 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java
> +		return environment.getProperty("feign.client.refresh-enabled", Boolean.class, false);
property added to `additional-spring-configuration-metadata.json`

2021-04-16 10:34 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +	 * meant to get Options bean from context with bean name.
Updated.

2021-04-16 10:34 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +
removed.

2021-04-16 10:34 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +	void setRefreshableClient(boolean refreshableClient) {
updated

2021-04-16 10:35 UTC, jas34 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableOptionsTest.java
> +	@DisabledForJreRange(min = JRE.JAVA_16)
Done

2021-04-16 10:35 UTC, jas34 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableOptionsTest.java
> +	@DisabledForJreRange(min = JRE.JAVA_16)
Done

2021-04-16 11:54 UTC, jas34 commented
> Hello, @jas34 . Thanks for submitting the PR. I have added some comments.
> Also, I have run some tests and have verified that the `Options` properties do not seem to be properly passed on to the request when `refresh-enabled` is set to `true` - please verify.
> In order to reproduce, use [this sample](https://github.com/spring-cloud-samples/feign-eureka), modify the SC version to `2020.0.3-SNAPSHOT` to pick your locally built changes and update [`application.yml`](https://gist.github.com/OlgaMaciaszek/ca501419887c588edf97292138fefe7e). Then when you debug at [`Client#execute`](https://github.com/OpenFeign/feign/blob/3ea3708cddef0d20c0bf443c18f2364c8d8df062/core/src/main/java/feign/Client.java#L104) the value set in properties is not passed on correctly, however with `refresh-enabled` set to `false` it is.

@OlgaMaciaszek I have checked as per the [sample ](https://github.com/spring-cloud-samples/feign-eureka) application provided.
I believe the proxy snapshot shown by the debugger has been misleading for you. When `feign.client.refresh-enabled`=`true` a scoped target CGLIB proxy bean gets created which does not show correct value in debugger because actual values are fetched when ObjectFactory.getObject() (in this case `org.springframework.cloud.openfeign.OptionsFactoryBean`) is invoked by FactoryBeanRegistrySupport.
In this case when options.connectTimeoutMillis() or any method of options beans is invoked it will return the correct value like 200 it is returning right now.
I have created a sample [POC](https://github.com/jas34/feign-eureka/blob/526-testing/client/src/main/java/demo/HelloClientApplication.java) (Refreshscope TestBean) to verify the same. There also the default value of field value will be 0 in debugger but returns an actual value of 10.

Let me know if you still find any issues.

2021-04-16 12:51 UTC, OlgaMaciaszek commented
>@OlgaMaciaszek I have checked as per the sample application provided.
I believe the proxy snapshot shown by the debugger has been misleading for you. When feign.client.refresh-enabled=true a scoped target CGLIB proxy bean gets created which does not show correct value in debugger because actual values are fetched when ObjectFactory.getObject() (in this case org.springframework.cloud.openfeign.OptionsFactoryBean) is invoked by FactoryBeanRegistrySupport.
In this case when options.connectTimeoutMillis() or any method of options beans is invoked it will return the correct value like 200 it is returning right now.
I have created a sample POC (Refreshscope TestBean) to verify the same. There also the default value of field value will be 0 in debugger but returns an actual value of 10.

Let me know if you still find any issues.
Ok, I have checked with some logging and in fact the values passed via debugger were incorrect. Will run some more tests.

2021-04-16 12:56 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableOptionsTest.java
> +	public void connectTimeoutShouldWorkWhenReadTimeoutNotSet() {
I did not mean to just remove the annotations but to only add tests that will run correctly also on JDK 16. These tests don't. Please modify the tests.

2021-04-16 13:23 UTC, jas34 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableOptionsTest.java
> +	public void connectTimeoutShouldWorkWhenReadTimeoutNotSet() {
I will check and get back to you. I thought it has been made compatible

2021-04-18 07:22 UTC, jas34 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableOptionsTest.java
> +	public void connectTimeoutShouldWorkWhenReadTimeoutNotSet() {
I have updated test strategy.
Implemented `feign.Client` with `OptionsTestClient` to return applicable Options from client as response `OptionsResponseForTests` and then use it for assertions.

2021-04-19 11:59 UTC, OlgaMaciaszek requested changes
@jas34 The added code looks good now. Please merge current `master` changes and resolve conflicts and document the newly added feature (in `spring-cloud-openfeign.adoc`), then run build with -Pdocs` before pushing to recreate auto-generated files.

2021-04-19 14:55 UTC, OlgaMaciaszek requested changes
@jas34 Have added some small comments regarding the documentation. Also, I am requesting @Buzzardo, to review the documentation changes.

2021-04-19 14:55 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +=== Spring RefreshScope Support
Change to Spring `@RefreshSchope` Support

2021-04-19 14:55 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +If feign client refresh is enabled then each feign client is created with `feign.Request.Options` as a refresh scoped bean. This means properties like `connectTimeout` and `readTimeout` can be refres
Pleasse capitalise "feign". Please add a hyphen in between in "refresh scoped".

2021-04-19 15:03 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +If feign client refresh is enabled then each feign client is created with `feign.Request.Options` as a refresh scoped bean. This means properties like `connectTimeout` and `readTimeout` can be refres
updates done

2021-04-19 15:05 UTC, Buzzardo requested changes

2021-04-19 15:05 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +If feign client refresh is enabled then each feign client is created with `feign.Request.Options` as a refresh scoped bean. This means properties like `connectTimeout` and `readTimeout` can be refres
Change to (incorporate Olga's request and my request):

If Feign client refresh is enabled, each feign client is created with `feign.Request.Options` as a refresh-scoped bean. This means properties such as `connectTimeout` and `readTimeout` can be refreshed against any Feign client instance through `POST /actuator/refresh`.

2021-04-19 15:05 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +By default refresh behaviour in feign clients is disabled. Use the following property to enable refresh behaviour.
Change to:

By default, refresh behavior in Feign clients is disabled. Use the following property to enable refresh behavior:

2021-04-19 15:05 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +TIP: DO NOT annotate `@FeignClient` interface with `@RefreshScope` annotation.
Change to:

TIP: DO NOT annotate the `@FeignClient` interface with the `@RefreshScope` annotation.

2021-04-19 15:26 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +By default refresh behaviour in feign clients is disabled. Use the following property to enable refresh behaviour.
changed.

2021-04-19 15:27 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +TIP: DO NOT annotate `@FeignClient` interface with `@RefreshScope` annotation.
changed

2021-04-19 16:04 UTC, Buzzardo approved these changes

2021-04-19 16:14 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +=== Spring RefreshScope Support
@jas34 This one change is still missing.

2021-04-19 16:14 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +=== Spring RefreshScope Support
Please add "@" and surround "@RefreshScope" with "`"

2021-04-19 16:23 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +=== Spring RefreshScope Support
Oh! I missed this.
Added as suggested above

2021-04-19 16:26 UTC, OlgaMaciaszek approved these changes
LGTM.

2021-04-19 16:27 UTC, merged