Add CircuitBreakerNameResolver
spring-cloud/spring-cloud-openfeign pull request #575
Opened 2021-07-20 08:15 UTC by bananayong

fixes dh-574

This PR includes an extension point for changing circuit breaker name.
`3.0.2` version included some change for a circuit breaker name. And this caused change of circuit breaker metric names.
CircuitBreakerNameResolver can be used for a developer to give own circuit breaker name.

2021-07-26 08:26 UTC, OlgaMaciaszek requested changes
@bananayong, thanks for submitting the PR. In general, the change looks good, however there are some issues to address:
- Please submit the PR against the `3.0.x` branch instead of `main`, so that the change is included in the `2020.0` release train as well. 
- Please add `@author` tags with your full name with any classes you've added or modified
- Have added a comment - please address
- Please document the new feature in `spring-cloud-openfeign.adoc`

2021-07-26 08:26 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/CircuitBreakerNameResolver.java
> +public interface CircuitBreakerNameResolver {
Please add Javadoc for interface and method. In the class-level one, please include your full name with the author tag and a `@since 2020.0.4` tag.

2021-07-27 04:44 UTC, bananayong commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/CircuitBreakerNameResolver.java
> +public interface CircuitBreakerNameResolver {
Done!

2021-07-27 04:45 UTC, bananayong commented
I fixed reviews. Please check again. Thx!

2021-07-27 08:54 UTC, OlgaMaciaszek approved these changes
LGTM.

2021-07-27 08:59 UTC, merged