Respect SpringDataWebProperties where possible
spring-cloud/spring-cloud-openfeign pull request #583
Opened 2021-07-26 08:10 UTC by quaff

`PageableSpringQueryMapEncoder` should use parameter names from `SpringDataWebProperties` if customized as well as `PageableSpringEncoder`

2021-07-26 15:03 UTC, spencergibb requested changes
Please add a test

2021-07-27 01:28 UTC, quaff commented
> Please add a test

@spencergibb test added, and `PageableEncoderTests` revised to cover `SpringDataWebProperties` supports.

2021-07-27 10:54 UTC, OlgaMaciaszek requested changes
@quaff Thanks for submitting the PR. Looks good. There are just some minor items to change:
- have added a comment - please address
- please add `@author` tag with your full name to javadocs of all the classes you've modified

2021-07-27 10:54 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/PageableEncoderTests.java
>   */
Please also add a test that verifies the default param names are used if not redefined in properties.

2021-07-28 01:12 UTC, quaff commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/PageableEncoderTests.java
>   */
Done @OlgaMaciaszek

2021-07-28 09:34 UTC, OlgaMaciaszek approved these changes
LGTM

2021-07-28 09:36 UTC, merged