gh-631 - Add support for customizing OAuth2FeignReqeustInterceptor.accessTokenProvider (injecting e.g. LoadBalancerInterceptor)
spring-cloud/spring-cloud-openfeign pull request #642
Opened 2021-12-08 08:18 UTC by voytech

**1. Added support to customize `OAuth2FeignReqeustInterceptor`'s internal `AccessTokenProvider` through `OAuth2FeignReqeustInterceptorBuilder` and `OAuth2FeignRequestInterceptorConfigurer`**. 

Before OAuth2FeignReqeustInterceptor is created and injected into context, instances of `OAuth2FeignRequestInterceptorConfigurer` are resolved and used to customize properties of internal `AccessTokenProvider`. 

**2. Extended `FeignAutoConfiguration` so that it can create  `OAuth2FeignReqeustInterceptor` with `RetryLoadBalancerInterceptor` or `LoadBalancerInterceptor` (depends what bean is already managed).** 

IMPORTANT: Load balancing is enabled only on flag: "feign.oauth2.load-balanced=true" in order to be backward compatible, but maybe it should be default behaviour in the same way as feign load balancing.

2021-12-08 15:48 UTC, OlgaMaciaszek requested changes
Hello, @voytech. Thanks for providing this PR. It looks good to me, however, I have added 2 comments - please address them. Also, please add documentation for the new feature to `spring-cloud-openfeign.adoc`.

 Also adding a member of the Spring Security team for an additional review.

2021-12-08 15:48 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/_configprops.adoc
> +|feign.oauth2.enabled | `false` | Enables the use OAuth2FeignRequestInterceptor in order to resolve access token.
Let's also add new properties to `additional-spring-configuration-metadata.json` for IDE support.

2021-12-08 15:48 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignAutoConfigurationTests.java
> +		assertThat(interceptor).isNotNull();
Let's use `org.springframework.boot.test.context.assertj.AssertableApplicationContext` for this assertion instead: 
```
AssertableApplicationContext context = AssertableApplicationContext.get(() -> ctx);
		assertThat(context).hasSingleBean(OAuth2FeignRequestInterceptor.class);
```

2021-12-08 15:50 UTC, OlgaMaciaszek commented
@eleftherias could you please review since it relates to Spring Security integration?

2021-12-08 15:52 UTC, OlgaMaciaszek commented
Fixes gh-631.

2021-12-08 16:09 UTC, voytech commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignAutoConfigurationTests.java
> +		assertThat(interceptor).isNotNull();
Sure, did not know about this assertion. Will change soon.

2021-12-08 16:10 UTC, voytech commented on docs/src/main/asciidoc/_configprops.adoc
> +|feign.oauth2.enabled | `false` | Enables the use OAuth2FeignRequestInterceptor in order to resolve access token.
Sure, will update soon.

2021-12-09 06:31 UTC, voytech commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignAutoConfigurationTests.java
> +		assertThat(interceptor).isNotNull();
I have used AssertableApplicationContext for all assertions. It turned out that this additional reflection util for assertions was not needed anymore, so things got simplified a bit.

2021-12-09 06:31 UTC, voytech commented on docs/src/main/asciidoc/_configprops.adoc
> +|feign.oauth2.enabled | `false` | Enables the use OAuth2FeignRequestInterceptor in order to resolve access token.
I have added both property flags

2021-12-09 11:52 UTC, OlgaMaciaszek requested changes
@voytech Thanks for adding the changes. Have added some cosmetic comments - please address them. The rest looks good to me. Will also add @Buzzardo as a reviewer to take a look at the doc section.

2021-12-09 11:52 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/_configprops.adoc
> +|feign.oauth2.load-balanced | `false` | Enables `LoadBalancerInterceptor` / `RetryloadBalancerInterceptor` for `OAuth2FeignRequestInterceptor.accessTokenProvider` in order to use load balancing when
Switch spelling to `load-balancing`.

2021-12-09 11:52 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +When flag is set to true, and oauth2 client context with resource details are present, a bean of class `OAuth2FeignRequestInterceptor` will be created. Since now, before each request, interceptor wil
Switch spelling to `load-balancing`. Switch from "should ensure that load balancer is on classpath" to  "should ensure that Spring Cloud LoadBalancer is on classpath" (it's the project official name).

2021-12-09 11:52 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +			"description": "Enables load balancing for oauth2 access token provider.",
Change spelling to `load-balancing`.

2021-12-09 16:08 UTC, Buzzardo requested changes

2021-12-09 16:08 UTC, Buzzardo commented on docs/src/main/asciidoc/_configprops.adoc
> +|feign.oauth2.load-balanced | `false` | Enables `LoadBalancerInterceptor` / `RetryloadBalancerInterceptor` for `OAuth2FeignRequestInterceptor.accessTokenProvider` in order to use load balancing when
Change the description to:

Enables `LoadBalancerInterceptor` or `RetryloadBalancerInterceptor` for `OAuth2FeignRequestInterceptor.accessTokenProvider` to use load balancing when resolving authentication token.

"load balancing" needs to be hyphenated when serving as an adjective ("load-balancing operations"). The rest of the time, it should be unhyphenated. I think we have been inconsistent about it, and I'm sure other products are inconsistent, too. But let's get it right here.

2021-12-09 16:08 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +When flag is set to true, and oauth2 client context with resource details are present, a bean of class `OAuth2FeignRequestInterceptor` will be created. Since now, before each request, interceptor wil
Change to:

When the flag is set to `true` and the oauth2 client context resource details are present, a bean of class `OAuth2FeignRequestInterceptor` is created. Before each request, the interceptor resolves the required access token and includes it as a header.

2021-12-09 16:08 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +Sometimes when load balancing is enabled for Feign clients, You may want to use load balancing for fetching access token too. To achieve this, You should ensure that load balancer is on classpath (`s
Change to:

Sometimes, when load balancing is enabled for Feign clients, you may want to use load balancing for fetching access tokens, too. To do so, you should ensure that the load balancer is on the classpath (`spring-cloud-starter-loadbalancer`) and explicitly enable load balancing for `OAuth2FeignRequestInterceptor` by setting the following flag:

2021-12-09 16:49 UTC, eleftherias approved these changes

2021-12-10 11:12 UTC, OlgaMaciaszek reviewed
@voytech Thanks for adding the changes. This comment has not been fully addressed yet: https://github.com/spring-cloud/spring-cloud-openfeign/pull/642#discussion_r765936661
When this is done, we will be able to get this merged.

2021-12-10 20:52 UTC, voytech commented
@OlgaMaciaszek Done.

2021-12-13 17:07 UTC, merged