fix cascading deserialization Spring Data's Page by setting @JsonIgnoreProperties(ignoreUnknown = true)
spring-cloud/spring-cloud-openfeign pull request #653
Opened 2021-12-27 19:57 UTC by nkonev

As discussed here https://github.com/spring-cloud/spring-cloud-openfeign/pull/636#discussion_r773598943

2021-12-27 20:11 UTC, nkonev commented
Build failure isn't related to change:
```
Could not transfer artifact org.codehaus.plexus:plexus-utils:jar:2.0.4 from/to central (https://repo.maven.apache.org/maven2): Connection reset
```

2021-12-29 07:03 UTC, KENNYSOFT reviewed
Alright, now the deserialization won't fail with unknown properties, so we may rollback `SimplePageImpl.getTotalPages()` and some methods to `@JsonProperty`, since v3.0.6 is a patch release and should not have any breaking changes. (The base branch of this PR should be 3.0.x also, to fix 3.0.6 https://github.com/spring-cloud/spring-cloud-openfeign/pull/636#pullrequestreview-817965591)

I've confirmed rollback `getTotalPages()`, `getNumberOfElements()`, `isFirst()`, `isLast()` from `@JsonIgnore` to `@JsonProperty` doesn't break any tests.

2022-01-11 19:37 UTC, nkonev commented
Hi @OlgaMaciaszek Can you bring it to 2021.0.1 and 2020.6 releases ?

2022-01-14 15:47 UTC, OlgaMaciaszek requested changes
@nkonev Thanks for submitting the fix. In general looks good. However, I've added a comment about a cosmetic issue - please address it. I don't think we're going to release `3.0.x` anymore, but we will be releasing `3.1.x` - could you please submit this against `3.1.x` instead of `main` so that we can include it in both release trains.

2022-01-14 15:47 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/PageJacksonModuleTests.java
> +		strings0.add("second element in cascaded serialization");
Let's rename it to something more meaningful, like `pageElements`.

2022-01-14 15:59 UTC, KENNYSOFT commented
> Thanks for submitting the fix. In general looks good. However, I've added a comment about a cosmetic issue - please address it. I don't think we're going to release `3.0.x` anymore, but we will be releasing `3.1.x` - could you please submit this against `3.1.x` instead of `main` so that we can include it in both release trains.

Sad to see you're dropping support for `3.0.x` release. It's in the Spring Cloud `2020.0.x` release train but really late 2020 (December) so it was only 13 months ago.

2022-01-14 16:21 UTC, OlgaMaciaszek approved these changes
LGTM.

2022-01-14 16:22 UTC, merged

2022-07-05 12:58 UTC, KENNYSOFT commented
@OlgaMaciaszek Why was this PR not cherry-picked to v3.0.7? 😭

2022-07-05 14:17 UTC, OlgaMaciaszek commented
@KENNYSOFT It was my mistake. Was looking for this discussion in issues. Did not realise it was in PRs instead. Will get a `3.0.8` released just for OpenFeign later this week to get this in.