Allow to inject custom HttpClient to programmatically created FeignClients
spring-cloud/spring-cloud-openfeign pull request #672
Opened 2022-01-25 16:22 UTC by f11h

The call of applyBuildCustomizers has been done before applying the HttpClient from FeignContext.

This PR moves the call at the end of the getTarget Method. It will allow to use a custom HttpClient. See #671 for more details.

2022-01-25 16:22 UTC, pivotal-cla commented
@f11h Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=672)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=672) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-01-25 16:23 UTC, pivotal-cla commented
@f11h Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=672)!

2022-01-27 12:58 UTC, OlgaMaciaszek requested changes
Hello, @f11h Thanks for submitting the PR. Have added a comment, please address. Also:
- please submit the fix against the `3.1.x` instead of `main`, so that the fix is also available for the `2021` release train
- please provide a test for the fix
- please add your full name and surname with `@author` tag to all the classes you've modified.

2022-01-27 12:58 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +		applyBuildCustomizers(context, builder);
Let's move this one line up.

2022-01-27 12:58 UTC, OlgaMaciaszek commented
Fixes gh-671.

2022-01-27 16:42 UTC, closed without merging

2022-01-27 16:43 UTC, f11h commented
I will create a new PR based on 3.1.x