Delete '/' at the end of url
spring-cloud/spring-cloud-openfeign pull request #707
Opened 2022-04-28 09:37 UTC by gorshik

In situation when we create FeignClient in this way:
@FeignClient(url = "https://localhost/", path = "api/v2")
We will get an error because of adding '/' in the beginning of the path in FeignClientsRegistrar.getPath, result will:
https://localhost//api/v2
To escape this situation we need to delete '/' at the end of url in FeignClientsRegistrar.getUrl

2022-04-28 09:37 UTC, pivotal-cla commented
@gorshik Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=707)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=707) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-04-28 09:39 UTC, pivotal-cla commented
@gorshik Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=707)!

2022-04-28 09:41 UTC, gorshik commented
@pivotal-cla This is an Obvious Fix

2022-04-28 15:50 UTC, spencergibb commented
Bug fixes like this don't typically qualify as an obvious fix

2022-07-25 13:58 UTC, OlgaMaciaszek requested changes
Hello @artem-gorshkov, thank you for submitting the PR. Please add a test that verifies your fix.

2024-10-11 11:28 UTC, OlgaMaciaszek commented
Closing in favour of https://github.com/spring-cloud/spring-cloud-openfeign/pull/1100.

2024-10-11 11:28 UTC, closed without merging