Customize load balanced requests according to the chosen ServiceInstance
spring-cloud/spring-cloud-openfeign pull request #735
Opened 2022-08-28 06:36 UTC by galaxy-sea

Applications can define their own LoadBalancerFeignRequestTransformer beans
which can modify the Request to be executed. These beans can be
@Ordered in case of multiple transformers.

reference [Transform the load-balanced HTTP request]( https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#transform-the-load-balanced-http-request)

2022-08-28 06:36 UTC, pivotal-cla commented
@galaxy-sea Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=735)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=735) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-08-28 06:39 UTC, pivotal-cla commented
@galaxy-sea Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=735)!

2022-08-30 08:21 UTC, galaxy-sea commented
@OlgaMaciaszek 
Can you check this PR.
I hope this function can be seen in the next release.

2022-08-30 14:12 UTC, OlgaMaciaszek commented
Hello, @galaxy-sea Thanks for submitting. Will review this week.

2022-08-31 10:37 UTC, OlgaMaciaszek requested changes
Thanks for submitting the PR @galaxy-sea. In general, LGTM. There's just one javadoc missing - have added a comment, please address. Also, have requested @Buzzardo to review the documentation change.

2022-08-31 10:37 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/LoadBalancerFeignRequestTransformer.java
> +	Request transformRequest(Request request, ServiceInstance instance);
Please add javadoc for method.

2022-08-31 11:55 UTC, galaxy-sea commented
Hello @OlgaMaciaszek, I have submitted the Javadoc

2022-08-31 12:01 UTC, OlgaMaciaszek requested changes
Please edit the javadoc.

2022-08-31 12:01 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/LoadBalancerFeignRequestTransformer.java
> +	 * ServiceInstance to transform the load-balanced Request.
Should be sth more about the method like "Allows transforming load-balanced requests based on the provided {@link ServiceInstance}`

2022-08-31 12:16 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/LoadBalancerFeignRequestTransformer.java
> +	 * ServiceInstance to transform the load-balanced Request.
Thank, I have re edited Javadoc

2022-08-31 12:21 UTC, OlgaMaciaszek approved these changes
Thanks @galaxy-sea. This look good to me now. Once @Buzzardo reviews the doc changes and any necessary fixes are made there, we'll be able to merge it.

2022-08-31 15:25 UTC, Buzzardo requested changes

2022-08-31 15:25 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +If multiple transformers are defined, they are applied in the order in which Beans are defined.
Uncapitalize "Beans".

2022-08-31 15:25 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +For `Request`, you need to implement and define `LoadBalancerFeignRequestTransformer` as follows:
Add a comma before "as follows".

2022-08-31 16:24 UTC, galaxy-sea commented
hello @Buzzardo , I have re edited spring-cloud-openfeign.adoc.

2022-08-31 18:25 UTC, Buzzardo approved these changes

2022-08-31 18:25 UTC, Buzzardo commented
Thank you. I approved the changes.

2022-09-01 09:38 UTC, merged

2022-09-01 11:55 UTC, galaxy-sea commented
Thank @OlgaMaciaszek @Buzzardo

2022-09-01 11:58 UTC, OlgaMaciaszek commented
Thanks for the contribution @galaxy-sea