Enable X-Forwarded Headers.
spring-cloud/spring-cloud-openfeign pull request #748
Opened 2022-09-07 05:14 UTC by galaxy-sea

`spring.cloud.loadbalancer.x-forwarded.enabled=true` to Enable X-Forwarded Headers.

2022-09-07 10:01 UTC, spencergibb commented
Can you please explain why this is needed? Feign isn't a proxy

2022-09-07 10:25 UTC, galaxy-sea commented
hello @spencergibb , `RestTemplate` migrates to `OpenFeign`. `RestTemplate` provides `org.springframework.cloud.loadbalancer.blocking.XForwardedHeadersTransforme`, but `OpenFeign` does not provide `XForwardedHeadersTransformer`

2022-09-08 05:24 UTC, galaxy-sea commented
Refer to [RestTemplate](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/XForwardedHeadersTransformer.java) and [WebClient](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/XForwardedHeadersTransformer.java) .


Check [Set 'X-Forwarded-*' header when using loadbalanced RestTemplate issus](https://github.com/spring-cloud/spring-cloud-commons/issues/116), Don't know why OpenFeign doesn't provide support

@spencergibb

2022-09-12 11:35 UTC, galaxy-sea commented
hello @spencergibb , Please consider merging this PR

2022-10-17 16:38 UTC, OlgaMaciaszek requested changes
Hello @galaxy-sea , thanks for submitting the PR. Looks good. There's a cosmetic issue - have added comment - please address. Also, please document this feature in `spring-cloud-openfeign.adoc`.

2022-10-17 16:38 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/loadbalancer/XForwardedHeadersTransformerTests.java
> +public class XForwardedHeadersTransformerTests {
Please remove unnecessary `public` modifier.

2022-10-18 05:25 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/loadbalancer/XForwardedHeadersTransformerTests.java
> +public class XForwardedHeadersTransformerTests {
I have modified

2022-10-18 05:26 UTC, galaxy-sea commented
hello @OlgaMaciaszek , I have updated the document,

2022-10-18 05:30 UTC, galaxy-sea commented
I think these documents should be placed in Spring Cloud Commons

2022-10-18 11:35 UTC, OlgaMaciaszek commented
@galaxy-sea it is already documented there. But it's good to reiterate here, since we add the code separately (there's no full parity between the OF LB client and the Commons LB clients).

2022-10-18 12:48 UTC, galaxy-sea commented
> @galaxy-sea it is already documented there. But it's good to reiterate here, since we add the code separately (there's no full parity between the OF LB client and the Commons LB clients).

@OlgaMaciaszek,  Thank you for unlocking my doubts

2022-10-18 13:07 UTC, OlgaMaciaszek approved these changes
Thanks, @galaxy-sea . LGTM.

2022-10-18 13:07 UTC, merged