Handle byte[] arrays correctly.(Fixes gh-741)
spring-cloud/spring-cloud-openfeign pull request #765
Opened 2022-10-05 23:46 UTC by pandaapo

Fixes #741

Make `AbstractFormWriter#isTypeOrCollection()` handle byte[] arrays correctly instead of casting byte[] to object[] directly.

2022-10-05 23:46 UTC, pivotal-cla commented
@pandaapo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=765)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=765) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-10-05 23:48 UTC, pivotal-cla commented
@pandaapo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=765)!

2022-10-06 00:19 UTC, spencergibb commented
Is copying the array the only way around this?

2022-10-11 09:38 UTC, OlgaMaciaszek commented
Thanks, @pandaapo . Will review today.

2022-10-17 12:45 UTC, OlgaMaciaszek requested changes
Thanks @pandaapo . The fix looks mostly good, but have added comments - please address them. Please add your full name with `@author` tag to the javadoc. Could you also add a test that will verify your changes (one that would fail before your change)? Additionally, could you submit these changes against `3.1.x` branch instead of `main` so that they get included in the upcoming `2021.x` releases as well?

2022-10-17 12:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/AbstractFormWriter.java
> +			Object one = Array.get(object, 0);
We should probably verify first if  the array is not empty.

2022-10-17 12:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/AbstractFormWriter.java
> +			return len > 1 && one != null && isType.test(one);
Shouldn't this be `>= 1`?

2022-10-18 11:19 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/AbstractFormWriter.java
> +			return len > 1 && one != null && isType.test(one);
Indeed, it is. In this case, let's not change it for now as there were no issues reported regarding that logic.

2022-10-18 16:23 UTC, OlgaMaciaszek commented
Closing in favour of https://github.com/spring-cloud/spring-cloud-openfeign/pull/774.

2022-10-18 16:23 UTC, closed without merging