Make feign.Target.url refreshable
spring-cloud/spring-cloud-openfeign pull request #766
Opened 2022-10-09 14:45 UTC by jas34

Refer #710

- Created a model class RefreshableUrl to wrap url.
- Created RefreshableUrlFactoryBean to create instance of RefreshableUrl bean with applicable configuration properties.
- Created RefreshableHardCodedTarget to serve url wrapped under RefreshableUrl whenever needed.
- `url` property added to FeignClientProperties#FeignClientConfiguration.
- FeignClientRegistrar:
   - created a private method to populate Bean definition for RefreshableUrl bean.
   - invoked private method during Feign bean definition registration phase.
 - FeignClientFactoryBean:
    - updated to supply RefreshableHardCodedTarget target instead of HardCodedTarget if URL is defined in the property `spring.cloud.openfeign.client.config.{client-name}.url` and `spring.cloud.openfeign.client.refresh-enabled=true`.
- added test cases.

Fixes gh-710.

2022-10-12 16:21 UTC, OlgaMaciaszek requested changes
Thanks for submitting the PR @jas34. I have added some comments - 1 major about the logic and the rest cosmetic about code style and documentation. Please address the comments. Also please merge new changes from `main` to resolve the conflicts.

2022-10-13 14:11 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +			return (T) loadBalance(builder, context, (HardCodedTarget<T>) resolveTarget(context, contextId));
1. Test case for the same scenario is available test case [withoutConfigUrlFromProperties](https://github.com/jas34/spring-cloud-openfeign/blob/0fdaaa25b1ac1b9a5f42b58f91a3e5ad697fb6c3/spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableUrlTest.java#L63). I have a plan to create the similar regression test case when refresh is disabled.

2. Ok. I will add relevant test case as well.

3.3. 'host is provided in the URL' do you mean URL is provided like this `@FeignClient(name="testClient", url="http://localhost:8081")`? and when you say 'host is provided in the URL' then you mean `@FeignClient(name="testClient")`?
  3.2.a. URL from the property `spring.cloud.openfeign.client.config.{contextId}.url` will be read only when refresh is enabled. Should we add a capbility to read property `spring.cloud.openfeign.client.config.{contextId}.url` for non-refreshable clients as well?

2022-10-13 14:35 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java
> -			String beanName = Request.Options.class.getCanonicalName() + "-" + contextId;
Now calling same private method to register both type of beans.

2022-10-13 14:35 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/RefreshableUrl.java
> +/**
Added.

2022-10-13 14:35 UTC, jas34 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableUrlTest.java
> +
Method names changed.

2022-10-13 14:36 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +		private String url;
added.

2022-10-17 12:14 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +			return (T) loadBalance(builder, context, (HardCodedTarget<T>) resolveTarget(context, contextId));
Also, I think we should ignore refresh and properties if the users set the URL via annotation. If it's there - they'll get the backwards compatible behaviour. They need to explicitly move it from the annotation to the properties to get the new behaviour. wdyt?

2022-10-17 12:27 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +		 * Feign client host URL config definition placeholder.
Please convert to sth along the lines of "Allows setting Feign client host URL. This value will only be taken into account if the `url` is not set in the `@FeignClient` annotation." to add more information on how this will work.

2022-10-17 12:27 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java
> +	 * This method is meant to register beans definition with refreshScope.
Please reword from "This method is meant to register" to "This method registers".

2022-10-17 12:27 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableUrlTest.java
> +public class FeignClientWithRefreshableUrlTest {
Please rename the class to `FeignClientWithRefreshableUrlTests`.

2022-10-17 12:27 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableUrlTest.java
> +public class FeignClientWithRefreshableUrlTest {
Please remove unnecessary `public` modifiers from the class and method signatures.

2022-10-17 12:27 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +	private <T> HardCodedTarget<T> resolveTarget(FeignContext context, String contextId) {
Ok. Can you add it to `FeignClientProperties ` as well?

2022-10-17 12:29 UTC, OlgaMaciaszek requested changes
Thanks for the updates @jas34 . I have resolved some conversations and added some new comments - please address. Also, please get add the logic changes that we've discussed.

2022-10-21 01:58 UTC, galaxy-sea commented
I like this feature

2022-10-23 12:24 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java
> +	 * This method is meant to create {@link RefreshableUrl} beans definition with
Done.

2022-10-23 12:24 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/RefreshableUrl.java
> + * This model will just wrap url inside an object so that relevant proxy instance can be
Done.

2022-10-23 12:25 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/RefreshableUrl.java
> +	private String url;
Done.

2022-10-23 12:30 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +			return (T) loadBalance(builder, context, (HardCodedTarget<T>) resolveTarget(context, contextId));
- Possible scenarios documented in [spring-cloud-openfeign.adoc](https://github.com/jas34/spring-cloud-openfeign/blob/main/docs/src/main/asciidoc/spring-cloud-openfeign.adoc#supported-ways-to-provide-url-to-a-feign-client)
- Logic implemented as per the documentation.
- Test cases also added to verify the same.

2022-10-23 12:30 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +	private <T> HardCodedTarget<T> resolveTarget(FeignContext context, String contextId) {
Added

2022-10-23 12:31 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java
> +		 * Feign client host URL config definition placeholder.
corrected.

2022-10-23 12:31 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java
> +	 * This method is meant to register beans definition with refreshScope.
Done.

2022-10-23 12:31 UTC, jas34 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableUrlTest.java
> +public class FeignClientWithRefreshableUrlTest {
Done.

2022-10-23 12:31 UTC, jas34 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientWithRefreshableUrlTest.java
> +public class FeignClientWithRefreshableUrlTest {
Done

2022-10-23 12:33 UTC, jas34 commented
@OlgaMaciaszek implemented logic for URL as per the above discussion.

2022-10-25 11:12 UTC, OlgaMaciaszek requested changes
Thanks a lot @jas34. This PR is nearly ready for merge. I have added some minor issue comments to the documentation changes, but will also request @Buzzardo to review the docs. I have also added one comment regarding the logic. Please discuss the reasoning behind that or modify it.

2022-10-25 11:12 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +		return (T) targeter.target(this, builder, context, (HardCodedTarget<T>) resolveTarget(context, contextId, url));
`(T)` casting is redundant here and can be removed.

2022-10-25 11:12 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +		FeignClientProperties.FeignClientConfiguration config = findConfigByKey(contextId);
Not sure why this exception? It's a valid scenario when there's no URL in either properties or annotation and it's being handled in line 414. Please provide your reasoning behind this or fix.

2022-10-25 11:12 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +spring.cloud.openfeign.client.refresh-enabled=true
Please add description for this code snippet above.

2022-10-25 11:12 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url will be resolved from configuration properties without load balancing. if
Please hyphenate "load-balancing".

2022-10-25 13:06 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +		FeignClientProperties.FeignClientConfiguration config = findConfigByKey(contextId);
In this method, `HardCodedTarget` or `RefreshableHardCodedTarget` needs url so that they can be created as per the applicable constructor. This method accepts url as a parameter or tries to resolve the same from properties if url passed as a param is found to be null/blank. In the case of the unavailability of url, there is a possibility that we return an invalid Target. In order to avoid the same exception has been thrown.

2022-10-25 13:10 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +		FeignClientProperties.FeignClientConfiguration config = findConfigByKey(contextId);
Ok, this can't probably happen due to the condition above, but we can leave it in place as an additional safeguard.

2022-10-25 13:14 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +spring.cloud.openfeign.client.refresh-enabled=true
Looks like a typo, added by mistake.

2022-10-25 13:14 UTC, jas34 commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
> +		return (T) targeter.target(this, builder, context, (HardCodedTarget<T>) resolveTarget(context, contextId, url));
Removed.

2022-10-25 13:24 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url will be resolved from configuration properties without load balancing. if
Done

2022-10-25 13:29 UTC, jas34 commented
> Thanks a lot @jas34. This PR is nearly ready for merge. I have added some minor issue comments to the documentation changes, but will also request @Buzzardo to review the docs. I have also added one comment regarding the logic. Please discuss the reasoning behind that or modify it.

All comments fixed.

2022-10-25 16:57 UTC, Buzzardo requested changes

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +* with url wrapped under `org.springframework.cloud.openfeign.RefreshableUrl`. This means url of Feign client if defined
Change to:

A URL wrapped under `org.springframework.cloud.openfeign.RefreshableUrl`. This means the URL of the Feign client, if defined

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +with the property `spring.cloud.openfeign.client.config.{feignName}.url` can be refreshed against any Feign client instance.
Change to:

with the `spring.cloud.openfeign.client.config.{feignName}.url` property, can be refreshed against any Feign client instance.

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +The above properties can be refreshed through `POST /actuator/refresh`.
Change to: 

You can refresh these properties through `POST /actuator/refresh`.

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +URL to a Feign client can be provided in any of the following ways:
Change to:

You can provide a URL to a Feign client in any of the following ways:

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url is provided in the `@FeignClient` annotation.
Change to:

|The URL is provided in the `@FeignClient` annotation.

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url will be resolved from url attribute of annotation without load-balancing.
Change to:

|The URL is resolved from the `url` attribute of the annotation, without load-balancing.

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url is provided in the `@FeignClient` annotation as well as in
Change to:

|The URL is provided in the `@FeignClient` annotation and in the

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|`@FeignClient(name="testClient", url="http://localhost:8081")` and property defined in application.yml as
Change to:

|`@FeignClient(name="testClient", url="http://localhost:8081")` and the property defined in `application.yml` as

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +| `@FeignClient(name="testClient")` and property defined in application.yml as
Change to:

| `@FeignClient(name="testClient")` and the property defined in `application.yml` as

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url will be resolved from configuration properties without load-balancing. if
Change to:

|The URL is resolved from configuration properties, without load-balancing. If

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +`spring.cloud.openfeign.client.refresh-enabled=true` then url defined in configuration properties can be refreshed as described in <<Spring `@RefreshScope` Support,Spring RefreshScope Support>>.
Change to:

spring.cloud.openfeign.client.refresh-enabled=true`, then the URL defined in configuration properties can be refreshed as described in <<Spring `@RefreshScope` Support,Spring RefreshScope Support>>.

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url is neither provided in the `@FeignClient` annotation nor in configuration properties.
Change to:

|The URL is neither provided in the `@FeignClient` annotation nor in configuration properties.

2022-10-25 16:57 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url will be resolved from name attribute of annotation with load balancing.
Change to:

|The URL is resolved from the name attribute of the annotation, with load balancing.

2022-10-25 17:37 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +with the property `spring.cloud.openfeign.client.config.{feignName}.url` can be refreshed against any Feign client instance.
Done

2022-10-25 17:37 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +* with url wrapped under `org.springframework.cloud.openfeign.RefreshableUrl`. This means url of Feign client if defined
Done

2022-10-25 17:38 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +The above properties can be refreshed through `POST /actuator/refresh`.
Done

2022-10-25 17:38 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +URL to a Feign client can be provided in any of the following ways:
Done

2022-10-25 17:39 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url is provided in the `@FeignClient` annotation.
Done

2022-10-25 17:39 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url will be resolved from url attribute of annotation without load-balancing.
Done

2022-10-25 17:40 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url is provided in the `@FeignClient` annotation as well as in
Done

2022-10-25 17:40 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|`@FeignClient(name="testClient", url="http://localhost:8081")` and property defined in application.yml as
Done

2022-10-25 17:41 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url will be resolved from url attribute of annotation without load-balancing.
Done

2022-10-25 17:41 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +Url provided in the configuration properties remains unused.
Done

2022-10-25 17:41 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url is not provided in the `@FeignClient` annotation but provided in configuration properties.
Done

2022-10-25 17:42 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +| `@FeignClient(name="testClient")` and property defined in application.yml as
Done

2022-10-25 17:43 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url will be resolved from configuration properties without load-balancing. if
Done

2022-10-25 17:43 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url is neither provided in the `@FeignClient` annotation nor in configuration properties.
Done

2022-10-25 17:44 UTC, jas34 commented on docs/src/main/asciidoc/spring-cloud-openfeign.adoc
> +|Url will be resolved from name attribute of annotation with load balancing.
Done

2022-10-26 09:32 UTC, merged