connectionRequestTimeout for httpClient Fixes gh-799
spring-cloud/spring-cloud-openfeign pull request #810
Opened 2022-12-20 14:57 UTC by galaxy-sea

Fixes issue [Can't config connection request timeout for http client #799](https://github.com/spring-cloud/spring-cloud-openfeign/issues/799)

2022-12-30 15:32 UTC, szpak commented
I had bumped into that problem recently and I've just wanted to report that future request :-).

It is especially useful, as "total" timeout to perform the request-response pair doesn't seem to be supported by HC5 - https://issues.apache.org/jira/browse/HTTPCLIENT-1074

2023-01-16 11:37 UTC, OlgaMaciaszek requested changes
Hello @galaxy-sea, thanks for submitting this PR. I've added a comment - please address it. Also, please submit these changes against `3.1.x` instead of `main`, so we'll get them included in the `2021.x` release train as well.

2023-01-16 11:37 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java
> +		public static final int DEFAULT_CONNECTION_REQUEST_TIMEOUT = 5;
In order to maintain compatibility, let's stick with the HC5 defualt connection request timeout (3 minutes).

2023-01-16 15:18 UTC, galaxy-sea commented
> Hello @galaxy-sea, thanks for submitting this PR. I've added a comment - please address it. Also, please submit these changes against `3.1.x` instead of `main`, so we'll get them included in the `2021.x` release train as well.

hello @OlgaMaciaszek, I resubmitted a PR for the 3.1. x branch . [pr#817](https://github.com/spring-cloud/spring-cloud-openfeign/pull/817)

2023-01-17 12:00 UTC, OlgaMaciaszek commented
Thanks @galaxy-sea . Closing in favour of https://github.com/spring-cloud/spring-cloud-openfeign/pull/817.

2023-01-17 12:01 UTC, closed without merging