okhttp supports custom protocols. gh-809
spring-cloud/spring-cloud-openfeign pull request #820
Opened 2023-01-20 03:18 UTC by galaxy-sea

hello @OlgaMaciaszek , Complete the `OkHttpClient` custom protocol, but `Client.Default` and `ApacheHttp5Client` do not support http2.

2023-02-01 13:15 UTC, OlgaMaciaszek requested changes
Hello, @galaxy-sea. Actually,  HTTP2 is supported by OkHttp and it's [enabled by default](https://github.com/square/okhttp/blob/5402ebaaa67ae05975e7d02490ef4003fdf3a4da/okhttp/src/jvmMain/kotlin/okhttp3/OkHttpClient.kt#L1144). However, this PR is still useful. I have added comments - please address them.

Also, there's [support in Apache HC5](https://hc.apache.org/httpcomponents-core-5.1.x/current/httpcore5-h2/apidocs/). We should add the support for it within gh-809 (can be in a separate PR) - will you work on that as well?

2023-02-01 13:15 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/protocol/FeignOkProtocolsTests.java
> +	void testFeignClientType() {
Please add an assertion to verify that the client has the `Protocol.H2_PRIOR_KNOWLEDGE` present.

2023-02-02 14:50 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignOkHttpConfigurationTests.java
> +	void shouldProtocols() {
done.

2023-02-02 14:50 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignOkHttpConfigurationTests.java
> +		assertThat(httpClient.protocols()).isEqualTo(List.of(Protocol.H2_PRIOR_KNOWLEDGE));
done.

2023-02-02 14:50 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/protocol/FeignOkProtocolsTests.java
> +	void testFeignClientType() {
done.

2023-02-02 14:51 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/protocol/Application.java
> +public class Application {
done.

2023-02-02 14:52 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/protocol/FeignOkProtocolsTests.java
> +	@Test
done. You're right.  I have deleted the relevant test code.

2023-02-03 11:10 UTC, OlgaMaciaszek requested changes
Thanks, @galaxy-sea. Have just added two cosmetic comments. Once this is done, we'll be able to merge it.

2023-02-03 11:21 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/protocol/FeignOkProtocolsTests.java
> +	public static class Application {
Expected `Expected protected static class`

2023-02-03 11:22 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/protocol/FeignOkProtocolsTests.java
> +
done.

2023-02-03 11:29 UTC, OlgaMaciaszek reviewed
Thanks, @galaxy-sea, I see the build is failing on checkstyle:
`/home/runner/work/spring-cloud-openfeign/spring-cloud-openfeign/spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignOkHttpConfigurationTests.java:20:1: 'javax.net.ssl.HostnameVerifier' should be separated from previous imports. `

2023-02-03 11:30 UTC, OlgaMaciaszek requested changes
Thanks, @galaxy-sea, the build is failing on checkstyle:
`/home/runner/work/spring-cloud-openfeign/spring-cloud-openfeign/spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignOkHttpConfigurationTests.java:20:1: 'javax.net.ssl.HostnameVerifier' should be separated from previous imports. `. Have added a comment - please fix.

2023-02-03 11:30 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignOkHttpConfigurationTests.java
> -
This is what is causing the build checkstyle failure - please revert this line deletion.

2023-02-03 11:35 UTC, galaxy-sea commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignOkHttpConfigurationTests.java
> -
Sorry, I resubmitted the code

2023-02-03 11:44 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignOkHttpConfigurationTests.java
> -
No problem, thanks.

2023-02-03 11:56 UTC, OlgaMaciaszek commented
@galaxy-sea I see there are some test failures that I would not expect as a result of your PR. Can you first merge changes from `origin/main` into your PR to get the updated artifact versions? If it still fails then, will take a closer look.

2023-02-03 12:18 UTC, galaxy-sea commented
> @galaxy-sea I see there are some test failures that I would not expect as a result of your PR. Can you first merge changes from `origin/main` into your PR to get the updated artifact versions? If it still fails then, will take a closer look.

I submit

2023-02-03 14:52 UTC, OlgaMaciaszek commented
Ok, @galaxy-sea - I'll take a look at it on Monday.

2023-02-07 11:38 UTC, OlgaMaciaszek commented
Hi, @galaxy-sea, this is happening because the `Protocol` class has been compiled without `- parameters`, which is necessary for AOT processing of the properties file. I have [modified it to use Strings instead](84ebabce1ddafeaef1e40d5ee529b9ff54d84cf7). Merged within gh-825. Thanks for your work on this issue @galaxy-sea.

2023-02-07 11:38 UTC, closed without merging