fallback support FacotryBean
spring-cloud/spring-cloud-openfeign pull request #823
Opened 2023-01-25 15:11 UTC by min1854

2023-02-02 15:16 UTC, OlgaMaciaszek requested changes
Hello @min1854, thanks for submitting the PR.  Please add your name and surname with the `@author` tag in the Javadoc of any class you've modified. Please add tests.

2023-02-02 15:18 UTC, OlgaMaciaszek commented
Fixes gh-822.

2023-02-02 15:36 UTC, min1854 commented
> Hello @min1854, thanks for submitting the PR. Please add your name and surname with the `@author` tag in the Javadoc of any class you've modified. Please add tests.

Ok, thank you. 
My localhost git user.name name is different from the github account name, do I need to change it to the github account name

2023-02-02 15:39 UTC, OlgaMaciaszek commented
> > Hello @min1854, thanks for submitting the PR. Please add your name and surname with the `@author` tag in the Javadoc of any class you've modified. Please add tests.
> 
> Ok, thank you. My localhost git user.name name is different from the github account name, do I need to change it to the github account name

No, just put the correct one in the javadoc.

2023-02-02 15:41 UTC, min1854 commented
> > > Hello @min1854, thanks for submitting the PR. Please add your name and surname with the `@author` tag in the Javadoc of any class you've modified. Please add tests.
> > 
> > 
> > Ok, thank you. My localhost git user.name name is different from the github account name, do I need to change it to the github account name
> 
> No, just put the correct one in the javadoc.



> > > Hello @min1854, thanks for submitting the PR. Please add your name and surname with the `@author` tag in the Javadoc of any class you've modified. Please add tests.
> > 
> > 
> > Ok, thank you. My localhost git user.name name is different from the github account name, do I need to change it to the github account name
> 
> No, just put the correct one in the javadoc.

I would like to ask if my javadoc @author  should use local user.name or should use the github account name

2023-02-02 15:45 UTC, spencergibb commented
It should be your name, not a user or github account name

2023-02-02 15:47 UTC, min1854 commented
> It should be your name, not a user or github account name

Ok, thanks.

2023-02-03 11:02 UTC, OlgaMaciaszek requested changes
Thanks for adding the test @min1854. Have added some comments, practically all cosmetic. Please address them, and we'll be able to get it merged.

2023-02-03 11:02 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +	public interface FactoryBeanFallbackFeign {
Please remove the unnecessary `public` keyword.

2023-02-03 11:02 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +	public interface OriginalFeign {
Please remove the unnecessary `public` keyword.

2023-02-03 11:02 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +	public void factoryBeanFallback() {
Please rename the test to `shouldRunFallbackFromBeanOrFactoryBean`.

2023-02-03 11:08 UTC, min1854 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +public class FallbackSupportFactoryBeanTests {
class modifier change to private?

2023-02-03 11:10 UTC, min1854 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +public class FallbackSupportFactoryBeanTests {
![image](https://user-images.githubusercontent.com/102911352/216589116-b5d446e2-35a9-4a24-8f26-5b662817e748.png)
Or is that it?

2023-02-03 11:11 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +public class FallbackSupportFactoryBeanTests {
No, just package level: `class FallbackSupportFactoryBeanTests`, with no added modifier.

2023-02-03 11:12 UTC, min1854 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +
Are these the empty lines

![image](https://user-images.githubusercontent.com/102911352/216589371-dd63bb22-d89c-4aa0-be8a-a092f1abb78b.png)

2023-02-03 11:16 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +
Yes, those were the lines I meant.

2023-02-03 11:19 UTC, min1854 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +
final result 
![image](https://user-images.githubusercontent.com/102911352/216590667-8d6faf21-8db6-4dba-b10b-1f9986132003.png)

Is that OK?

2023-02-03 11:32 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +
Yes, it is @min1854. Please also address the other comments. There's no need to add screenshot - just address all the comments and push the change - will review again once it's all done.

2023-02-03 11:35 UTC, min1854 commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +
Ok, I really appreciate your help

2023-02-03 11:45 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +
Thanks for working on the issue :)

2023-02-03 11:54 UTC, min1854 commented
> Thanks for adding the test @min1854. Have added some comments, practically all cosmetic. Please address them, and we'll be able to get it merged.

Am I done?Is there anything else I need to do?

2023-02-03 12:16 UTC, min1854 commented
> Thanks for adding the test @min1854. Have added some comments, practically all cosmetic. Please address them, and we'll be able to get it merged.

Should I not click on 'conversation as resolved.'.Is that right. I'm sorry. I think I misunderstood

2023-02-03 14:53 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +public class FallbackSupportFactoryBeanTests {
@min1854 do not mark them as resolved. We'll resolve them. Yes, it's like the code from screenshot. Please commit and. push the changed code.

2023-02-03 14:54 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +	public void shouldRunFallbackFromBeanOrFactoryBean() {
Please remove the unnecessary `public` keyword here as well.

2023-02-03 15:05 UTC, OlgaMaciaszek requested changes
Hello, @min1854, there are still unaddressed comments. Please add changes.

2023-02-06 11:13 UTC, OlgaMaciaszek requested changes
Thanks, @min1854, have added 2 more comments, including one in a previous conversation. These are just tiny cosmetic changes. Please implement them and we'll be able to get this merged.

2023-02-06 11:13 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +public class FallbackSupportFactoryBeanTests {
@min1854 it still is `public class FallbackSupportFactoryBeanTests `. Please change to `class FallbackSupportFactoryBeanTests`, without the `public` keyword.

2023-02-06 11:13 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/FallbackSupportFactoryBeanTests.java
> +	public static class TestConfiguration {
Could this be changed to a `private static class` as well.

2023-02-07 11:19 UTC, OlgaMaciaszek approved these changes
Thanks, @min1854. LGTM.

2023-02-07 11:19 UTC, merged

2023-02-07 11:24 UTC, OlgaMaciaszek commented
No, it's fine. This issue is now closed. Thanks for working on it.

2023-02-07 11:26 UTC, min1854 commented
Ok, thank you