Add HttpClientBuilderCustomizer interface
spring-cloud/spring-cloud-openfeign pull request #890
Opened 2023-09-04 02:34 UTC by bananayong

Hi, Olga.
I always thank for your efforts.

I would like to provide the ability for a user to customize settings, In addition to leveraging existing Spring Cloud settings.

In the previous version, ApacheHttpClientFactory interface exists. So I can customize HttpClientBuilder additionally.
But, in the current version, there is no method for HttpClientBuilder configurations.

Thank you!

2023-09-04 03:04 UTC, spencergibb commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java
> +		HttpClientBuilderCustomizer customizer = customizerProvider.getIfAvailable();
Usually there is a list of this type of bean so there can be multiple contributions

2023-09-04 03:11 UTC, bananayong commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java
> +		HttpClientBuilderCustomizer customizer = customizerProvider.getIfAvailable();
Done. thx fast feedback!

2023-09-15 06:53 UTC, bananayong commented
I hope to ship this PR in the next release. 🙏

2023-09-26 13:03 UTC, OlgaMaciaszek commented
Thanks for the PR, @bananayong . Could you please add a test and document the feature?

2023-09-26 13:04 UTC, OlgaMaciaszek requested changes
Thanks for the PR @bananayong. Please add a test and document the feature.

2023-09-26 18:17 UTC, bananayong commented
@OlgaMaciaszek 
I added a test case and simple explanation for a `HttpClientBuilderCustomizer` interface.

Thank your feedback!

2023-10-06 03:30 UTC, bananayong commented
Is there any progress? @OlgaMaciaszek

2023-10-25 06:21 UTC, yong-kurly commented
If I need more work, please let me know.

2023-10-31 14:38 UTC, OlgaMaciaszek requested changes
Thanks, @bananayong, looks good. Please just update the license entries to `-2023` and add your full name with `@author` tag to the javadocs of the classes you've changed - then it'll be ready to merge.

2023-10-31 16:26 UTC, bananayong commented
@OlgaMaciaszek Done. Please review 🙇

2023-11-02 17:15 UTC, OlgaMaciaszek commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java
> +	public interface HttpClientBuilderCustomizer {
Thanks @bananayong - one more thing: please a dd a Javadocs for this interface and method.

2023-11-03 08:42 UTC, yong-kurly commented on spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java
> +	public interface HttpClientBuilderCustomizer {
Added javadoc.

2023-11-03 10:50 UTC, OlgaMaciaszek approved these changes
Thanks, @bananayong. LGTM.

2023-11-03 11:20 UTC, merged