(docs): Replace `@RequestMapping` with newer `@GetMapping` (etc.)
spring-cloud/spring-cloud-openfeign pull request #957
Opened 2023-12-19 21:02 UTC by AlexElin

See the subject

2024-01-11 10:53 UTC, OlgaMaciaszek requested changes
Hello @AlexElin, thanks for submitting the PR. Have added a comment. Please address it.

2024-01-11 10:53 UTC, OlgaMaciaszek commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> -	@RequestMapping(method = RequestMethod.GET, value = "/stores")
Please leave this one as `@RequestMapping` - like this we showcase various possible options.

2024-01-23 21:22 UTC, AlexElin commented on docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
> -	@RequestMapping(method = RequestMethod.GET, value = "/stores")
changed

2024-01-24 11:19 UTC, OlgaMaciaszek approved these changes
Thanks @AlexElin. LGTM.

2024-01-24 11:19 UTC, merged