Fix simple typo on Configuration Properties page
spring-cloud/spring-cloud-openfeign pull request #993
Opened 2024-02-22 01:27 UTC by djkeh

This pr fixes typo in description of the configuration property `spring.cloud.openfeign.circuitbreaker.group.enabled`.
Thanks.

2024-02-22 01:27 UTC, pivotal-cla commented
@djkeh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=993)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=993) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-02-22 01:29 UTC, pivotal-cla commented
@djkeh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=993)!

2024-03-19 14:02 UTC, OlgaMaciaszek requested changes
Hello @djkeh. Thanks for the contribution. This file is auto-generated. You need to change it in `spring-cloud-openfeign-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json` instead. Then you can just run `./mvnw clean install -Pdocs` to regenerate this file.

2024-03-19 19:14 UTC, djkeh commented
Thanks @OlgaMaciaszek, I understood and fixed the typo using the right way.

2024-03-20 10:45 UTC, OlgaMaciaszek approved these changes
Thanks @djkeh. LGTM.

2024-03-20 10:45 UTC, merged